const URL='https://jjqhvruppafpumcthmwe.supabase.co';
const KEY='sb_publishable_02hhRG8bgDOqSFxva8IMvQ_zWTLMa3G';
const TOKEN_KEY='afrn_admin_access_token';
const $=id=>document.getElementById(id);
let token=localStorage.getItem(TOKEN_KEY)||'', comps=[], clubs=[], assignments=[], selected='';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function api(path,opt={}){const h={apikey:KEY,Authorization:'Bearer '+(token||KEY),'Content-Type':'application/json',...(opt.headers||{})};const r=await fetch(URL+'/rest/v1/'+path,{...opt,headers:h});if(!r.ok){const t=await r.text();throw new Error(r.status+' '+t)}const t=await r.text();return t?JSON.parse(t):[]}
async function login(){const email=$('email').value.trim(),password=$('password').value;if(!email||!password)return msg('Jaza email na password.');$('login').disabled=true;msg('Inathibitisha...');try{const r=await fetch(URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.error_description||data.msg||'Login imekataa');token=data.access_token;localStorage.setItem(TOKEN_KEY,token);$('loginCard').classList.add('hidden');$('adminApp').classList.remove('hidden');await load()}catch(e){token='';localStorage.removeItem(TOKEN_KEY);msg('❌ '+e.message)}finally{$('login').disabled=false}}
function msg(x){$('loginMsg').textContent=x}
async function load(){try{[comps,clubs]=await Promise.all([api('competitions?select=id,name,season,competition_type,division,status,logo_url&order=name'),api('clubs?select=id,name,short_name,division,zone,logo_url,afrn_club_id&order=name')]);$('competition').innerHTML=comps.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+' • '+esc(c.season||'')+'</option>').join('');if(!comps.length){$('compMeta').textContent='Hakuna mashindano yaliyohifadhiwa online.';return}selected=$('competition').value;await refresh();}catch(e){if(String(e.message).startsWith('401')||String(e.message).startsWith('403'))logout();else alert('Admin data: '+e.message)}}
async function refresh(){selected=$('competition').value;const c=comps.find(x=>String(x.id)===String(selected));$('compMeta').textContent=c?('Msimu: '+(c.season||'—')+' • Aina: '+(c.competition_type||'—')+' • Daraja: '+(c.division||'—')):'';assignments=await api('competition_teams?competition_id=eq.'+encodeURIComponent(selected)+'&select=id,competition_id,club_id,group_name');renderLists()}
function renderLists(){const ids=new Set(assignments.map(a=>String(a.club_id)));$('registered').innerHTML=assignments.map(a=>{const c=clubs.find(x=>String(x.id)===String(a.club_id));return '<div class="admin-row"><span><b>'+esc(c?.name||a.club_id)+'</b><small>'+esc(c?.division||'')+(a.group_name?' • Group '+esc(a.group_name):'')+'</small></span><button class="danger" data-remove="'+esc(a.id)+'">Ondoa</button></div>'}).join('')||'<div class="empty">Hakuna timu iliyosajiliwa.</div>';filterAvailable(ids);document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeTeam(b.dataset.remove))}
function filterAvailable(ids){const q=$('teamSearch').value.trim().toLowerCase();const list=clubs.filter(c=>!ids.has(String(c.id))&&((c.name||'').toLowerCase().includes(q)||(c.short_name||'').toLowerCase().includes(q)));$('available').innerHTML=list.slice(0,80).map(c=>'<div class="admin-row"><span><b>'+esc(c.name||c.short_name)+'</b><small>'+esc(c.division||'')+(c.zone?' • '+esc(c.zone):'')+'</small></span><button data-add="'+esc(c.id)+'">＋ Ongeza</button></div>').join('')||'<div class="empty">Hakuna timu nyingine.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addTeam(b.dataset.add))}
async function addTeam(clubId){try{const c=comps.find(x=>String(x.id)===String(selected));let group=null;if(String(c?.name||'').toLowerCase().includes('upendo')){const n=assignments.length;group=String.fromCharCode(65+Math.floor(n/4));if(group>'F')group=null}await api('competition_teams',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({competition_id:selected,club_id:clubId,group_name:group})});await refresh()}catch(e){alert('Timu haijaongezwa: '+e.message)}}
async function removeTeam(id){if(!confirm('Ondoa timu hii kwenye mashindano?'))return;try{await api('competition_teams?id=eq.'+encodeURIComponent(id),{method:'DELETE'});await refresh()}catch(e){alert('Timu haijaondolewa: '+e.message)}}
function logout(){token='';localStorage.removeItem(TOKEN_KEY);$('adminApp').classList.add('hidden');$('loginCard').classList.remove('hidden');}
$('login').onclick=login;$('logout').onclick=logout;$('competition').onchange=refresh;$('teamSearch').oninput=()=>{const ids=new Set(assignments.map(a=>String(a.club_id)));filterAvailable(ids)};if(token){$('loginCard').classList.add('hidden');$('adminApp').classList.remove('hidden');load().catch(()=>logout())}