const leagueKey='afrn_leagues';
const teamKey='afrn_master_teams';
const SUPABASE_URL='https://jjqhvruppafpumcthmwe.supabase.co';
const SUPABASE_KEY='sb_publishable_02hhRG8bgDOqSFxva8IMvQ_zWTLMa3G';
const defaults=[{name:'Ligi Kuu',type:'League',division:'Ligi Kuu',season:'2026/2027',teams:[]},{name:'Daraja la I',type:'League',division:'Daraja la I',season:'2026/2027',teams:[]},{name:'Daraja la II',type:'League',division:'Daraja la II',season:'2026/2027',teams:[]},{name:'Daraja la III',type:'League',division:'Daraja la III',season:'2026/2027',teams:[]},{name:'UPENDO WA WAKIMBIZI CUP',type:'Tournament',division:'Daraja la I',season:'2026',teams:[],source:'supabase',sourceCompetitionId:'3b55884e-05bc-4d83-832e-3addcd97d970'}];
function getLeagues(){const x=localStorage.getItem(leagueKey);if(!x){localStorage.setItem(leagueKey,JSON.stringify(defaults));return defaults}const a=JSON.parse(x);if(!a.some(l=>String(l.name).toLowerCase()==='upendo wa wakimbizi cup')){a.push(defaults[4]);localStorage.setItem(leagueKey,JSON.stringify(a))}return a}
function getTeams(){const x=localStorage.getItem(teamKey);return x?JSON.parse(x):[]}
function saveTeams(x){localStorage.setItem(teamKey,JSON.stringify(x))}
function divisionOf(l){return l.division||l.name}
function teamsForLeague(l){return getTeams().filter(t=>divisionOf(l)==='Open'||t.division===divisionOf(l))}
function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]))}
function render(){const box=document.getElementById('leagues');if(!box)return;box.innerHTML=getLeagues().map((l,i)=>{const cup=l.type==='Tournament';const teams=cup?[]:teamsForLeague(l);return `<article class="competition-card" onclick="openLeague(${i})"><div class="comp-head"><div><div class="comp-title">${cup?'🏆 ':''}${esc(l.name)}</div><div class="comp-meta">${esc(l.season)} • ${cup?'Mashindano/Cup':esc(divisionOf(l))}</div></div><span class="badge">${cup?'CUP':'LIGA'}</span></div>${cup?`<div class="score-row"><div>Makundi</div><div class="score">A–F</div><div>Knockout</div></div>`:`<div class="score-row"><div><b>${teams.length}</b><div class="status">Timu</div></div><div class="score">—</div><div><b>0</b><div class="status">Mechi leo</div></div></div><div class="modules"><div class="module">📅 Ratiba</div><div class="module">🏁 Matokeo</div><div class="module">📊 Msimamo</div><div class="module">⚽ Wafungaji</div><div class="module">🟨 Kadi</div><div class="module">📈 Stats</div><div class="module">📚 Historia</div><div class="module">⚖️ Nidhamu</div></div>`}<button class="open">${cup?'Fungua Mashindano':'Fungua Ligi'} →</button></article>`}).join('')}
function openLeague(i){location.href=`competition.html?id=${i}`}
function setupStatsSelector(){const select=document.getElementById('statsCompetition'),button=document.getElementById('openSelectedStats');if(!select||!button)return;const leagues=getLeagues();select.innerHTML='<option value="">— Chagua ligi —</option>'+leagues.map((l,i)=>`<option value="${i}">${esc(l.name)} • ${esc(l.season||'')}</option>`).join('');select.onchange=()=>{button.disabled=select.value===''};button.onclick=()=>{if(select.value!=='')location.href=`competition.html?id=${encodeURIComponent(select.value)}#stats`}}

function statsCss(){if(document.getElementById('homeStatsCss'))return;const s=document.createElement('style');s.id='homeStatsCss';s.textContent='.home-stats{margin-top:12px}.home-stat-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.home-stat-card{border:1px solid #e1e6ee;border-radius:12px;background:#fff;padding:12px}.home-stat-title{font-size:11px;font-weight:900;color:#697487;text-transform:uppercase;margin-bottom:9px}.home-stat-values{display:grid;grid-template-columns:1fr 45px 1fr;align-items:center;text-align:center;gap:5px}.home-stat-values b{font-size:16px}.home-stat-values span{display:block;font-size:10px;color:#8791a0}.home-stat-bar{height:6px;background:#edf0f3;border-radius:99px;overflow:hidden;display:flex;margin-top:9px}.home-stat-bar i{height:100%;display:block}.home-stat-bar i:first-child{background:#1473e6}.home-stat-bar i:last-child{background:#7c8797}.home-stat-note{font-size:12px;color:#697487;margin:8px 0}.home-stat-table{margin-top:12px;overflow-x:auto;border:1px solid #e1e6ee;border-radius:10px}.home-stat-table table{min-width:420px}@media(max-width:650px){.home-stat-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function showHomeStatsMessage(msg){const h=document.getElementById('homeStats');if(h)h.innerHTML='<div class="empty">'+esc(msg)+'</div>'}
function statValue(rows,side,key,mode){const vals=rows.map(r=>Number(r[side+'_'+key])).filter(Number.isFinite);if(!vals.length)return null;if(mode==='avg')return vals.reduce((a,b)=>a+b,0)/vals.length;return vals.reduce((a,b)=>a+b,0)}
function statCard(label,h,a,d=0,pct=false){if(h==null&&a==null)return '';const total=(h||0)+(a||0),hp=total?(h||0)/total*100:50;return '<div class="home-stat-card"><div class="home-stat-title">'+label+'</div><div class="home-stat-values"><div><b>'+(h==null?'—':h.toFixed(d))+(pct&&h!=null?'%':'')+'</b><span>NYUMBANI</span></div><strong>VS</strong><div><b>'+(a==null?'—':a.toFixed(d))+(pct&&a!=null?'%':'')+'</b><span>UGENINI</span></div></div>'+(total?'<div class="home-stat-bar"><i style="width:'+hp+'%"></i><i style="width:'+(100-hp)+'%"></i></div>':'')+'</div>'}
async function findCompetitionId(l){if(l?.sourceCompetitionId)return l.sourceCompetitionId;const q=encodeURIComponent(l?.name||'');try{let x=await supa('competitions?select=id,name,title&name=eq.'+q+'&limit=1');if(x[0]?.id)return x[0].id;x=await supa('competitions?select=id,name,title&title=eq.'+q+'&limit=1');return x[0]?.id||null}catch(e){return null}}
async function loadHomeStats(l){const h=document.getElementById('homeStats');if(!h)return;statsCss();h.innerHTML='<div class="empty">⏳ Inapakia takwimu za '+esc(l.name)+'...</div>';try{const cid=await findCompetitionId(l);if(!cid){showHomeStatsMessage('Ligi hii bado haijaunganishwa na data ya mechi kwenye Supabase.');return}const [matches,allStats,clubs]=await Promise.all([supa('matches?competition_id=eq.'+cid+'&select=id,home_team_id,away_team_id,home_score,away_score'),supa('match_statistics?select=*'),supa('clubs?select=id,name')]);const ids=new Set(matches.map(m=>String(m.id))),rows=allStats.filter(s=>ids.has(String(s.match_id)));if(!rows.length){showHomeStatsMessage('Hakuna rekodi za kina za takwimu kwa ligi hii bado.');return}const metrics=[['Possession','possession',1,true,'avg'],['Shots','shots',0,false,'sum'],['Shots on target','shots_on_target',0,false,'sum'],['Shots off target','shots_off_target',0,false,'sum'],['Blocked shots','blocked_shots',0,false,'sum'],['Corners','corners',0,false,'sum'],['Fouls','fouls',0,false,'sum'],['Offsides','offsides',0,false,'sum'],['Big chances','big_chances',0,false,'sum'],['xG','xg',2,false,'sum'],['Passes','passes',0,false,'sum'],['Pass accuracy','pass_accuracy',1,true,'avg'],['Saves','saves',0,false,'sum'],['Crosses','crosses',0,false,'sum'],['Duels won','duels_won',0,false,'sum'],['Momentum','momentum',1,false,'avg']];const cards=metrics.map(m=>statCard(m[0],statValue(rows,'home',m[1],m[4]),statValue(rows,'away',m[1],m[4]),m[2],m[3])).join('');const names=Object.fromEntries(clubs.map(x=>[String(x.id),x.name]));const team={};matches.forEach(m=>{const h=String(m.home_team_id),a=String(m.away_team_id);team[h]??={name:names[h]||h,played:0,goals:0};team[a]??={name:names[a]||a,played:0,goals:0};team[h].played++;team[a].played++;team[h].goals+=Number(m.home_score)||0;team[a].goals+=Number(m.away_score)||0});const trs=Object.values(team).sort((x,y)=>y.goals-x.goals||y.played-x.played).map((t,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(t.name)+'</td><td>'+t.played+'</td><td><b>'+t.goals+'</b></td></tr>').join('');h.innerHTML='<p class="home-stat-note">Takwimu za <b>'+esc(l.name)+'</b> kutoka kwenye mechi '+matches.length+' zenye rekodi za statistics.</p><div class="home-stat-grid">'+cards+'</div><div class="home-stat-table"><table><thead><tr><th>#</th><th>Timu</th><th>Mechi</th><th>Mabao</th></tr></thead><tbody>'+trs+'</tbody></table></div>'}catch(e){console.error(e);showHomeStatsMessage('Takwimu hazikupatikana kwa sasa. Jaribu ku-refresh ukurasa.')}}
const modal=document.getElementById('modal');document.getElementById('newLeague').onclick=()=>modal.classList.remove('hidden');document.getElementById('close').onclick=()=>modal.classList.add('hidden');document.getElementById('save').onclick=()=>{const name=document.getElementById('leagueName').value.trim(),season=document.getElementById('season').value.trim(),type=document.getElementById('competitionType').value,division=document.getElementById('leagueDivision').value;if(!name)return alert('Andika jina la ligi.');const leagues=getLeagues();leagues.push({name,type,division,season:season||'2026/2027',teams:[]});localStorage.setItem(leagueKey,JSON.stringify(leagues));modal.classList.add('hidden');document.getElementById('leagueName').value='';render();setupStatsSelector()};
const teamModal=document.getElementById('teamModal');document.getElementById('newTeam').onclick=()=>teamModal.classList.remove('hidden');document.getElementById('teamClose').onclick=()=>teamModal.classList.add('hidden');document.getElementById('teamSave').onclick=()=>{const jina=document.getElementById('teamName').value.trim(),division=document.getElementById('teamDivision').value,zone=document.getElementById('teamZone').value.trim();if(!jina)return alert('Andika jina la timu.');const teams=getTeams();if(teams.some(t=>t.jina.toLowerCase()===jina.toLowerCase()&&t.division===division))return alert('Timu hii tayari ipo katika daraja hili.');teams.push({id:'TEAM-'+Date.now(),jina,division,zone,P:0,W:0,D:0,L:0,GF:0,GA:0,Pts:0,Red:0,Yellow:0});saveTeams(teams);teamModal.classList.add('hidden');document.getElementById('teamName').value='';document.getElementById('teamZone').value='';render()};
async function supa(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY}});if(!r.ok)throw new Error('Supabase '+r.status);return r.json()}
function localDate(offset){const d=new Date();d.setDate(d.getDate()+offset);return d.toLocaleDateString('en-CA',{timeZone:'Africa/Dar_es_Salaam'})}
function statusLabel(s){const x=String(s||'').toLowerCase();if(['live','in_progress','playing'].includes(x))return '🔴 LIVE';if(['finished','completed'].includes(x))return 'FT';if(['postponed'].includes(x))return 'POSTPONED';return 'UPCOMING'}
async function loadMatchFeed(view='today'){
 const feed=document.getElementById('matchFeed'),title=document.getElementById('matchTitle'),status=document.getElementById('matchStatus');
 if(!feed)return;const offset=view==='yesterday'?-1:view==='tomorrow'?1:0;title.textContent=view==='today'?'Mechi za Leo':view==='yesterday'?'Matokeo ya Jana':view==='tomorrow'?'Mechi za Kesho':'Mechi Zote';status.textContent='Inapakia...';feed.innerHTML='<div class="empty">Inapakia mechi...</div>';
 try{const [matches,clubs]=await Promise.all([supa('matches?select=id,competition_id,home_team_id,away_team_id,match_date,match_time,venue,home_score,away_score,status,match_number,notes&order=match_date,match_time'),supa('clubs?select=id,name,short_name,division,logo_url')]);const names=Object.fromEntries(clubs.map(c=>[c.id,c.name||c.short_name||c.id]));const date=localDate(offset);let rows=view==='all'?matches:matches.filter(m=>String(m.match_date||'').slice(0,10)===date);rows.sort((a,b)=>String(a.match_date+a.match_time).localeCompare(String(b.match_date+b.match_time)));if(!rows.length){feed.innerHTML='<div class="empty">Hakuna mechi zilizopangwa kwa siku hii.</div>';status.textContent='0 mechi';return}feed.innerHTML=rows.map(m=>`<a class="match-row-link" href="match.html?id=${encodeURIComponent(m.id)}"><span><small>${esc(m.match_time||'—')} • ${esc(m.venue||'Uwanja haujawekwa')}</small><strong>${esc(names[m.home_team_id]||m.home_team_id)}</strong><strong>${esc(names[m.away_team_id]||m.away_team_id)}</strong></span><b>${m.home_score==null?'—':esc(m.home_score)+' - '+esc(m.away_score)}<small>${statusLabel(m.status)}</small></b></a>`).join('');status.textContent=`${rows.length} mechi`;}catch(e){feed.innerHTML=`<div class="empty">⚠️ ${esc(e.message)}. Mfumo wa ligi bado unafanya kazi.</div>`;status.textContent='Data haikupatikana'}}
document.querySelectorAll('.quick').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.quick').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadMatchFeed(b.dataset.view)}));
render();setupStatsSelector();loadMatchFeed('today');