const leagueKey='afrn_leagues';
const teamKey='afrn_master_teams';
const defaults=[
{name:'Ligi Kuu',division:'Ligi Kuu',season:'2026/2027',teams:[]},
{name:'Daraja la I',division:'Daraja la I',season:'2026/2027',teams:[]},
{name:'Daraja la II',division:'Daraja la II',season:'2026/2027',teams:[]},
{name:'Daraja la III',division:'Daraja la III',season:'2026/2027',teams:[]}
];
function getLeagues(){const x=localStorage.getItem(leagueKey);if(!x){localStorage.setItem(leagueKey,JSON.stringify(defaults));return defaults}return JSON.parse(x)}
function getTeams(){const x=localStorage.getItem(teamKey);return x?JSON.parse(x):[]}
function saveTeams(x){localStorage.setItem(teamKey,JSON.stringify(x))}
function divisionOf(l){return l.division||l.name}
function teamsForLeague(l){return getTeams().filter(t=>t.division===divisionOf(l))}
function renderMsimamo(timu){const rows=[...timu];rows.sort((a,b)=>{if(b.Pts!==a.Pts)return b.Pts-a.Pts;if(b.GF!==a.GF)return b.GF-a.GF;if(a.GA!==b.GA)return a.GA-b.GA;if(a.Red!==b.Red)return a.Red-b.Red;return a.Yellow-b.Yellow});return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Timu</th><th>P</th><th>GF</th><th>GA</th><th>Pts</th></tr></thead><tbody>${rows.map((t,i)=>`<tr><td>${i+1}</td><td>${esc(t.jina)}</td><td>${t.P||0}</td><td>${t.GF||0}</td><td>${t.GA||0}</td><td><b>${t.Pts||0}</b></td></tr>`).join('')}</tbody></table></div>`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){const box=document.getElementById('leagues');box.innerHTML=getLeagues().map((l,i)=>{const teams=teamsForLeague(l);const standings=teams.map(t=>({jina:t.jina,P:t.P||0,GF:t.GF||0,GA:t.GA||0,Pts:t.Pts||0,GD:(t.GF||0)-(t.GA||0),Red:t.Red||0,Yellow:t.Yellow||0}));return `<article class="card"><h2>${esc(l.name)}</h2><div class="season">Msimu: ${esc(l.season)} • Daraja: <b>${esc(divisionOf(l))}</b></div><div class="modules"><div class="module">👥 Timu: ${teams.length}</div><div class="module">📅 Ratiba</div><div class="module">🏁 Matokeo</div><div class="module">📊 Standings</div><div class="module">⚽ Wafungaji</div><div class="module">🟨🟥 Kadi</div><div class="module">📈 Statistics</div><div class="module">📚 Historia</div><div class="module">📄 Reports</div><div class="module">⚖️ Nidhamu</div></div><h3>Timu za ${esc(divisionOf(l))}</h3>${teams.length?`<ul class="team-list">${teams.map(t=>`<li><b>${esc(t.jina)}</b><span>${esc(t.division)}${t.zone?' • '+esc(t.zone):''}</span></li>`).join('')}</ul>`:'<div class="empty">Hakuna timu iliyosajiliwa katika daraja hili bado.</div>'}<h3>Msimamo</h3>${renderMsimamo(standings)}<button class="open" onclick="openLeague(${i})">Fungua Ligi</button></article>`}).join('')}
function openLeague(i){const l=getLeagues()[i];alert(`Ligi: ${l.name}\nDaraja: ${divisionOf(l)}\nMsimu: ${l.season}\n\nMfumo umefunga ligi hii kwenye timu za daraja hili tu.`)}
const modal=document.getElementById('modal');document.getElementById('newLeague').onclick=()=>modal.classList.remove('hidden');document.getElementById('close').onclick=()=>modal.classList.add('hidden');document.getElementById('save').onclick=()=>{const name=document.getElementById('leagueName').value.trim(),season=document.getElementById('season').value.trim();if(!name)return alert('Andika jina la ligi.');const leagues=getLeagues();leagues.push({name,division:name,season:season||'2026/2027',teams:[]});localStorage.setItem(leagueKey,JSON.stringify(leagues));modal.classList.add('hidden');document.getElementById('leagueName').value='';render()};
const teamModal=document.getElementById('teamModal');document.getElementById('newTeam').onclick=()=>teamModal.classList.remove('hidden');document.getElementById('teamClose').onclick=()=>teamModal.classList.add('hidden');document.getElementById('teamSave').onclick=()=>{const jina=document.getElementById('teamName').value.trim(),division=document.getElementById('teamDivision').value,zone=document.getElementById('teamZone').value.trim();if(!jina)return alert('Andika jina la timu.');const teams=getTeams();if(teams.some(t=>t.jina.toLowerCase()===jina.toLowerCase()&&t.division===division))return alert('Timu hii tayari ipo katika daraja hili.');teams.push({id:'TEAM-'+Date.now(),jina,division,zone,P:0,W:0,D:0,L:0,GF:0,GA:0,Pts:0,Red:0,Yellow:0});saveTeams(teams);teamModal.classList.add('hidden');document.getElementById('teamName').value='';document.getElementById('teamZone').value='';render()};
render();