const SUPABASE_URL='https://jjqhvruppafpumcthmwe.supabase.co';const SUPABASE_KEY='sb_publishable_02hhRG8bgDOqSFxva8IMvQ_zWTLMa3G';const TOKEN_KEY='afrn_auth_session';
const $=id=>document.getElementById(id);
function session(){try{return JSON.parse(localStorage.getItem(TOKEN_KEY)||'null')}catch(e){return null}}
function msg(text,type='info'){const x=$('authMessage');x.textContent=text;x.className='auth-message '+type}
async function authFetch(path,options={}){const headers={apikey:SUPABASE_KEY,'Content-Type':'application/json',...(options.headers||{})};const r=await fetch(SUPABASE_URL+path,{...options,headers});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch(e){d={message:t}}if(!r.ok)throw new Error(d.error_description||d.msg||d.message||'Ombi la akaunti limekataa.');return d}
function saveSession(d){localStorage.setItem(TOKEN_KEY,JSON.stringify({access_token:d.access_token,refresh_token:d.refresh_token,expires_at:d.expires_at,user:d.user||null}));}
async function loadUser(){const s=session();if(!s?.access_token)return null;try{const d=await authFetch('/auth/v1/user',{headers:{Authorization:'Bearer '+s.access_token}});return d}catch(e){localStorage.removeItem(TOKEN_KEY);return null}}
function showPanel(id){['loginPanel','signupPanel','forgotPanel','accountPanel'].forEach(x=>$(x).classList.toggle('hidden',x!==id));$('authMessage').classList.add('hidden')}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const b=$('loginBtn');b.disabled=true;try{const d=await authFetch('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('loginEmail').value.trim(),password:$('loginPassword').value})});saveSession(d);msg('Umeingia kwa mafanikio.','success');setTimeout(()=>location.href='index.html',500)}catch(err){msg(err.message,'error')}finally{b.disabled=false}});
$('signupForm').addEventListener('submit',async e=>{e.preventDefault();const b=$('signupBtn');b.disabled=true;try{const d=await authFetch('/auth/v1/signup',{method:'POST',body:JSON.stringify({email:$('signupEmail').value.trim(),password:$('signupPassword').value,data:{full_name:$('signupName').value.trim()}})});if(d.access_token){saveSession(d);msg('Akaunti imeundwa.','success');setTimeout(()=>location.href='index.html',600)}else{msg('Akaunti imeundwa. Angalia email yako kuthibitisha akaunti kabla ya kuingia.','success');showPanel('loginPanel')}}catch(err){msg(err.message,'error')}finally{b.disabled=false}});
$('forgotForm').addEventListener('submit',async e=>{e.preventDefault();const b=$('forgotSubmit');b.disabled=true;try{const redirect=location.origin+location.pathname.replace(/[^/]*$/,'')+'auth.html';await authFetch('/auth/v1/recover',{method:'POST',body:JSON.stringify({email:$('forgotEmail').value.trim(),redirect_to:redirect})});msg('Link ya kubadilisha password imetumwa kwenye email yako.','success')}catch(err){msg(err.message,'error')}finally{b.disabled=false}});
$('signupShow').onclick=()=>showPanel('signupPanel');$('loginShow').onclick=()=>showPanel('loginPanel');$('forgotBtn').onclick=()=>showPanel('forgotPanel');$('forgotBack').onclick=()=>showPanel('loginPanel');
$('logoutBtn').onclick=async()=>{const s=session();try{if(s?.access_token)await authFetch('/auth/v1/logout',{method:'POST',headers:{Authorization:'Bearer '+s.access_token}})}catch(e){}localStorage.removeItem(TOKEN_KEY);showPanel('loginPanel');msg('Umetoka kwenye akaunti.','success')};
(async()=>{const u=await loadUser();if(u){$('accountName').textContent=u.user_metadata?.full_name||u.email?.split('@')[0]||'Akaunti';$('accountEmail').textContent=u.email||'';showPanel('accountPanel')}})();