/* AFRN Football Centre — advanced cross-linked statistics layer */
const AFRN_API='https://jjqhvruppafpumcthmwe.supabase.co/rest/v1/';
const AFRN_KEY='sb_publishable_02hhRG8bgDOqSFxva8IMvQ_zWTLMa3G';
const H={apikey:AFRN_KEY,Authorization:'Bearer '+AFRN_KEY};
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function afrnGet(t,q=''){const r=await fetch(AFRN_API+t+'?'+q,{headers:H});if(!r.ok)throw Error(t+' '+r.status);return r.json();}
function evType(v){return String(v||'').toLowerCase().replace(/[ -]/g,'_');}
function pname(p){return p?.full_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||'Mchezaji';}
function eventCount(es,id,type){return es.filter(e=>String(e.player_id)===String(id)&&evType(e.event_type).includes(type)).length;}
function addBox(title,html){const el=document.createElement('section');el.className='card afrn-pro';el.innerHTML='<div class="section-head"><h2>'+title+'</h2></div>'+html;document.querySelector('main')?.appendChild(el);return el;}
async function playerCentre(){
 const id=new URLSearchParams(location.search).get('id');if(!id)return;
 const [p,events,shots,matches,clubs,comps]=await Promise.all([
  afrnGet('players','id=eq.'+encodeURIComponent(id)+'&select=*'),
  afrnGet('match_events','player_id=eq.'+encodeURIComponent(id)+'&select=match_id,event_type,minute,club_id'),
  afrnGet('match_shots','player_id=eq.'+encodeURIComponent(id)+'&select=match_id,shot_type,xg'),
  afrnGet('matches','select=id,competition_id,match_date,home_team_id,away_team_id,home_score,away_score,status&order=match_date.desc'),
  afrnGet('clubs','select=id,name'),
  afrnGet('competitions','select=id,name,season,status')
 ]);if(!p.length)return;
 const pm=p[0],cm=Object.fromEntries(clubs.map(x=>[String(x.id),x.name])),co=Object.fromEntries(comps.map(x=>[String(x.id),x]));
 const byMatch=new Set([...events.map(x=>String(x.match_id)),...shots.map(x=>String(x.match_id))]);
 const rows=matches.filter(m=>byMatch.has(String(m.id)));
 const seasons=[...new Set(rows.map(m=>String(co[m.competition_id]?.season||'—')))].filter(x=>x&&x!=='—');
 const box=addBox('📊 Season & Competition Centre','<div class="filters"><label>Season <select id="proSeason"><option value="all">Misimu yote</option>'+seasons.map(s=>'<option>'+E(s)+'</option>').join('')+'</select></label><label>Competition <select id="proComp"><option value="all">Mashindano yote</option>'+[...new Set(rows.map(m=>String(m.competition_id)))].map(cid=>'<option value="'+E(cid)+'">'+E(co[cid]?.name||'Competition')+'</option>').join('')+'</select></label></div><div id="proPlayerStats"></div>');
 const render=()=>{const se=document.getElementById('proSeason').value,ci=document.getElementById('proComp').value;const r=rows.filter(m=>(se==='all'||String(co[m.competition_id]?.season||'')===se)&&(ci==='all'||String(m.competition_id)===ci));const mids=new Set(r.map(m=>String(m.id)));const es=events.filter(e=>mids.has(String(e.match_id))),ss=shots.filter(x=>mids.has(String(x.match_id)));const goals=es.filter(e=>['goal','goals','goal_scored'].includes(evType(e.event_type))).length;const assists=es.filter(e=>evType(e.event_type).includes('assist')).length;const yellow=es.filter(e=>evType(e.event_type).includes('yellow')).length;const red=es.filter(e=>evType(e.event_type).includes('red')).length;const xg=ss.reduce((a,x)=>a+(Number(x.xg)||0),0);document.getElementById('proPlayerStats').innerHTML='<div class="quick-grid"><div><b>'+r.length+'</b><span>Appearances*</span></div><div><b>'+goals+'</b><span>Goals</span></div><div><b>'+assists+'</b><span>Assists</span></div><div><b>'+yellow+'/'+red+'</b><span>Yellow / Red</span></div><div><b>'+ss.length+'</b><span>Shots</span></div><div><b>'+ss.filter(x=>['goal','on_target'].includes(String(x.shot_type))).length+'</b><span>On Target</span></div><div><b>'+xg.toFixed(2)+'</b><span>xG</span></div><div><b>'+r.filter(m=>m.status==='FINISHED'||(m.home_score!=null&&m.away_score!=null)).length+'</b><span>Completed</span></div></div><p class="muted">* Appearance huhesabiwa kutoka kwenye mechi zenye event/shot ya mchezaji; haibuni data ambayo haijawekwa.</p>';};
 document.getElementById('proSeason').onchange=render;document.getElementById('proComp').onchange=render;render();
}
async function teamCentre(){
 const id=new URLSearchParams(location.search).get('id');if(!id)return;
 const [clubs,matches,events,stats,comps]=await Promise.all([afrnGet('clubs','id=eq.'+encodeURIComponent(id)+'&select=*'),afrnGet('matches','or=(home_team_id.eq.'+encodeURIComponent(id)+',away_team_id.eq.'+encodeURIComponent(id)+')&select=id,competition_id,match_date,home_team_id,away_team_id,home_score,away_score,status&order=match_date.desc'),afrnGet('match_events','club_id=eq.'+encodeURIComponent(id)+'&select=match_id,event_type,player_id'),afrnGet('match_statistics','select=*'),afrnGet('competitions','select=id,name,season,status')]);if(!clubs.length)return;
 const co=Object.fromEntries(comps.map(x=>[String(x.id),x]));const seasons=[...new Set(matches.map(m=>String(co[m.competition_id]?.season||'—')))].filter(x=>x!=='—');
 const box=addBox('📊 Team Season Centre','<div class="filters"><label>Season <select id="proTeamSeason"><option value="all">Misimu yote</option>'+seasons.map(s=>'<option>'+E(s)+'</option>').join('')+'</select></label><label>Competition <select id="proTeamComp"><option value="all">Mashindano yote</option>'+[...new Set(matches.map(m=>String(m.competition_id)))].map(x=>'<option value="'+E(x)+'">'+E(co[x]?.name||'Competition')+'</option>').join('')+'</select></label></div><div id="proTeamStats"></div><div id="proTeamHistory" class="stats-list"></div>');
 const render=()=>{const se=document.getElementById('proTeamSeason').value,ci=document.getElementById('proTeamComp').value;const r=matches.filter(m=>(se==='all'||String(co[m.competition_id]?.season||'')===se)&&(ci==='all'||String(m.competition_id)===ci));let w=0,d=0,l=0,gf=0,ga=0;for(const m of r){if(m.home_score==null||m.away_score==null)continue;const home=String(m.home_team_id)===String(id),a=Number(home?m.home_score:m.away_score),b=Number(home?m.away_score:m.home_score);gf+=a;ga+=b;if(a>b)w++;else if(a===b)d++;else l++;}const mids=new Set(r.map(m=>String(m.id)));const ss=stats.filter(s=>mids.has(String(s.match_id)));const avg=k=>ss.length?(ss.reduce((a,s)=>a+(Number(s['home_'+k])||0)*(String(matches.find(m=>String(m.id)===String(s.match_id))?.home_team_id)===String(id)?1:0)+(Number(s['away_'+k])||0)*(String(matches.find(m=>String(m.id)===String(s.match_id))?.away_team_id)===String(id)?1:0),0)/ss.length).toFixed(k==='xg'?2:1):'—';document.getElementById('proTeamStats').innerHTML='<div class="quick-grid"><div><b>'+r.length+'</b><span>Matches</span></div><div><b>'+w+'</b><span>Wins</span></div><div><b>'+d+'</b><span>Draws</span></div><div><b>'+l+'</b><span>Losses</span></div><div><b>'+gf+':'+ga+'</b><span>GF:GA</span></div><div><b>'+(gf-ga)+'</b><span>GD</span></div><div><b>'+(w*3+d)+'</b><span>Points</span></div><div><b>'+ss.length+'</b><span>Matches with stats</span></div></div>';document.getElementById('proTeamHistory').innerHTML='<div class="info">Historia hii imegawanywa kwa Season/Competition na inatumia mechi halisi za timu.</div>'+r.slice(0,10).map(m=>'<a class="player-match-row" href="match.html?id='+E(m.id)+'"><span><b>'+E(co[m.competition_id]?.name||'Competition')+'</b><small>'+E(m.match_date||'—')+'</small></span><strong>'+(m.home_score??'—')+' - '+(m.away_score??'—')+'</strong></a>').join('');};
 document.getElementById('proTeamSeason').onchange=render;document.getElementById('proTeamComp').onchange=render;render();
}
async function competitionHistory(){
 const idParam=new URLSearchParams(location.search).get('id');const leagues=JSON.parse(localStorage.getItem('afrn_leagues')||'[]');const c=leagues[Number(idParam)];if(!c)return;
 const name=c.name||'';let comps=[];try{comps=await afrnGet('competitions','select=id,name,season,start_date,end_date,status&name=eq.'+encodeURIComponent(name)+'&order=season.desc');}catch(e){return}
 if(!comps.length)return;const el=addBox('📚 Competition History','<div class="stats-list">'+comps.map(x=>'<a class="player-match-row" href="competition.html?source='+encodeURIComponent(x.id)+'"><span><b>'+E(x.name)+'</b><small>Season '+E(x.season||'—')+' • '+E(x.status||'—')+'</small></span><strong>→</strong></a>').join('')+'</div>');el.scrollIntoView({block:'nearest'});
}
(async()=>{try{if(document.getElementById('playerApp'))await playerCentre();else if(document.getElementById('teamApp'))await teamCentre();else if(document.getElementById('app'))await competitionHistory();}catch(e){console.warn('AFRN advanced centre',e);}})();
