(()=>{
const UPENDO_ID='3b55884e-05bc-4d83-832e-3addcd97d970';
const esc=s=>String(s??'').replace(/[&<>\"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[x]));
async function statsApi(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY}});if(!r.ok)throw new Error('Supabase '+r.status);return r.json()}
function num(v){return typeof v==='number'&&Number.isFinite(v)?v:null}
function fmt(v,d=0){return v==null?'—':Number(v).toFixed(d)}
function sum(rows,side,key){return rows.reduce((n,r)=>n+(num(r[side+'_'+key])??0),0)}
function avg(rows,side,key){const a=rows.map(r=>num(r[side+'_'+key])).filter(v=>v!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function weighted(rows,side){let total=0,weighted=0;rows.forEach(r=>{const p=num(r[side+'_passes']),a=num(r[side+'_pass_accuracy']);if(p!=null&&a!=null){total+=p;weighted+=p*a}});return total?weighted/total:avg(rows,side,'pass_accuracy')}
function getCompetition(){const leagues=JSON.parse(localStorage.getItem('afrn_leagues')||'[]');const raw=new URLSearchParams(location.search).get('id')||'';return leagues.find(x=>String(x.sourceCompetitionId||x.id||'')===String(raw))||(/^\d+$/.test(raw)?leagues[Number(raw)]:null)}
async function getCompetitionId(c){if(c?.sourceCompetitionId)return c.sourceCompetitionId;if(String(c?.name||'').toUpperCase()==='UPENDO WA WAKIMBIZI CUP')return UPENDO_ID;if(!c?.name)return null;try{const rows=await statsApi('competitions?select=id,name,title,season&or=(name.eq.'+encodeURIComponent(c.name)+',title.eq.'+encodeURIComponent(c.name)+')&limit=1');return rows[0]?.id||null}catch(e){console.warn('Competition lookup failed',e);return null}}
function addStyle(){if(document.getElementById('afrnStatsCss'))return;const s=document.createElement('style');s.id='afrnStatsCss';s.textContent='.afrn-stat-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:12px}.afrn-stat-card{border:1px solid #e1e6ee;border-radius:12px;background:#fff;padding:12px}.afrn-stat-title{font-size:11px;font-weight:900;color:#697487;text-transform:uppercase;margin-bottom:9px}.afrn-stat-values{display:grid;grid-template-columns:1fr 55px 1fr;align-items:center;text-align:center;gap:6px}.afrn-stat-values b{font-size:16px}.afrn-stat-values span{display:block;font-size:10px;color:#8791a0}.afrn-stat-bar{height:6px;background:#edf0f3;border-radius:99px;overflow:hidden;display:flex;margin-top:9px}.afrn-stat-bar i{height:100%;display:block}.afrn-stat-bar i:first-child{background:#1473e6}.afrn-stat-bar i:last-child{background:#7c8797}.afrn-stat-note{font-size:12px;color:#697487}.afrn-stat-empty{padding:14px;background:#f7f8fa;border-radius:10px;color:#697487;font-size:13px}.afrn-stat-table{margin-top:14px;overflow-x:auto;border:1px solid #e1e6ee;border-radius:10px}.afrn-stat-table table{min-width:480px}@media(max-width:650px){.afrn-stat-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function card(label,h,a,d=0,pct=false){if(h==null&&a==null)return '';const total=(h??0)+(a??0);const hp=total?((h??0)/total)*100:50;return '<div class="afrn-stat-card"><div class="afrn-stat-title">'+label+'</div><div class="afrn-stat-values"><div><b>'+fmt(h,d)+(pct&&h!=null?'%':'')+'</b><span>NYUMBANI</span></div><strong>VS</strong><div><b>'+fmt(a,d)+(pct&&a!=null?'%':'')+'</b><span>UGENINI</span></div></div>'+(total?'<div class="afrn-stat-bar"><i style="width:'+hp+'%"></i><i style="width:'+(100-hp)+'%"></i></div>':'')+'</div>'}
async function render(){const host=document.getElementById('stats');if(!host)return;const c=getCompetition(),cid=await getCompetitionId(c);if(!cid){host.innerHTML='<p class="afrn-stat-note">Ligi hili bado halijaunganishwa na mashindano yaliyopo kwenye mfumo wa mechi.</p>';return;}host.dataset.afrnStatsReady='1';addStyle();host.innerHTML='<div class="afrn-stat-empty">⏳ Inapakia takwimu za mashindano...</div>';try{const [matches,allStats,clubs]=await Promise.all([statsApi('matches?competition_id=eq.'+cid+'&select=id,home_team_id,away_team_id,home_score,away_score'),statsApi('match_statistics?select=*'),statsApi('clubs?select=id,name')]);const ids=new Set(matches.map(m=>String(m.id))),rows=allStats.filter(s=>ids.has(String(s.match_id)));const names=Object.fromEntries(clubs.map(x=>[String(x.id),x.name]));if(!rows.length){host.innerHTML='<p class="afrn-stat-note">Hakuna rekodi za kina zilizopo bado. Zitaonekana mara tu zitakapoingizwa kwenye Match Centre.</p>';return}
const metrics=[['Possession','possession',1,true,'avg'],['Shots','shots',0,false,'sum'],['Shots on target','shots_on_target',0,false,'sum'],['Shots off target','shots_off_target',0,false,'sum'],['Blocked shots','blocked_shots',0,false,'sum'],['Corners','corners',0,false,'sum'],['Fouls','fouls',0,false,'sum'],['Offsides','offsides',0,false,'sum'],['Big chances','big_chances',0,false,'sum'],['xG','xg',2,false,'sum'],['Passes','passes',0,false,'sum'],['Pass accuracy','pass_accuracy',1,true,'weighted'],['Saves','saves',0,false,'sum'],['Crosses','crosses',0,false,'sum'],['Duels won','duels_won',0,false,'sum'],['Momentum','momentum',1,false,'avg']];
const cards=metrics.map(m=>{const [label,key,d,pct,mode]=m;let h,a;if(mode==='avg'){h=avg(rows,'home',key);a=avg(rows,'away',key)}else if(mode==='weighted'){h=weighted(rows,'home');a=weighted(rows,'away')}else{h=sum(rows,'home',key);a=sum(rows,'away',key)}return card(label,h,a,d,pct)}).join('');
const team={};matches.forEach(m=>{const h=String(m.home_team_id),a=String(m.away_team_id);team[h]??={name:names[h]||h,played:0,goals:0};team[a]??={name:names[a]||a,played:0,goals:0};team[h].played++;team[a].played++;team[h].goals+=Number(m.home_score)||0;team[a].goals+=Number(m.away_score)||0});
const trs=Object.values(team).sort((a,b)=>b.goals-a.goals||b.played-a.played).map((t,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(t.name)+'</td><td>'+t.played+'</td><td><b>'+t.goals+'</b></td></tr>').join('');
host.innerHTML='<div><p class="afrn-stat-note">Takwimu zimejumlishwa kutoka kwenye mechi '+matches.length+' za mashindano haya pekee. Hakuna thamani iliyotengenezwa.</p><div class="afrn-stat-grid">'+cards+'</div><div class="afrn-stat-table"><table><thead><tr><th>#</th><th>Timu</th><th>Mechi</th><th>Mabao</th></tr></thead><tbody>'+trs+'</tbody></table></div></div>';
}catch(e){console.error(e);host.innerHTML='<div class="afrn-stat-empty">Takwimu hazikupatikana kwa sasa. Jaribu ku-refresh ukurasa.</div>'}}
function boot(){const obs=new MutationObserver(()=>{const h=document.getElementById('stats');if(h&&!h.dataset.afrnStatsReady)render()});obs.observe(document.body,{childList:true,subtree:true});setTimeout(render,300);setInterval(render,30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();