const leagues=JSON.parse(localStorage.getItem('afrn_leagues')||'[]');
const id=Number(new URLSearchParams(location.search).get('id'));
const c=leagues[id];
const app=document.getElementById('app');
const SUPABASE_URL='https://jjqhvruppafpumcthmwe.supabase.co';
const SUPABASE_KEY='sb_publishable_02hhRG8bgDOqSFxva8IMvQ_zWTLMa3G';
const UPENDO_ID='3b55884e-05bc-4d83-832e-3addcd97d970';
function esc(s){return String(s??'').replace(/[&<>\"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[x]))}
async function api(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY}});if(!r.ok)throw new Error('Supabase: '+r.status);return r.json()}
function score(m){if(m.home_score==null||m.away_score==null)return '—';return `${m.home_score} - ${m.away_score}`}
function stage(notes=''){const m=String(notes);const x=m.match(/AFRN_STAGE=([^|]+)/);if(x)return x[1];for(const g of ['A','B','C','D','E','F'])if(m.includes('Group '+g))return 'GROUP '+g;return 'GROUP STAGE'}
function teamLink(id,name,meta=''){return `<a class="team-link-card" href="team.html?id=${encodeURIComponent(id)}"><b>${esc(name)}</b><small>${esc(meta)}</small></a>`}
function matchLink(m,home,away){return `<a class="match-row-link" href="match.html?id=${encodeURIComponent(m.id)}"><span>${esc(home)}</span><b>${score(m)}</b><span>${esc(away)}</span></a>`}
function aggregateStandings(matches,clubIds){const map={};clubIds.forEach(cid=>map[cid]={club_id:cid,played:0,wins:0,draws:0,losses:0,goals_for:0,goals_against:0,points:0,yellow_cards:0,red_cards:0});matches.filter(m=>m.home_score!=null&&m.away_score!=null).forEach(m=>{const h=String(m.home_team_id),a=String(m.away_team_id);if(!map[h]||!map[a])return;const hs=Number(m.home_score),as=Number(m.away_score);map[h].played++;map[a].played++;map[h].goals_for+=hs;map[h].goals_against+=as;map[a].goals_for+=as;map[a].goals_against+=hs;if(hs>as){map[h].wins++;map[a].losses++;map[h].points+=3}else if(hs<as){map[a].wins++;map[h].losses++;map[a].points+=3}else{map[h].draws++;map[a].draws++;map[h].points++;map[a].points++}});return Object.values(map)}
function fixtureRows(matches,names,prefix){return matches.map(m=>{const live=['LIVE','IN_PLAY','1H','2H','ET','PAUSED'].includes(String(m.status||'').toUpperCase());return `<div class="fixture-item" data-prefix="${prefix}" data-date="${esc(m.match_date||'')}" data-played="${m.home_score!=null&&m.away_score!=null?1:0}">${matchLink(m,names[m.home_team_id]||m.home_team_id,names[m.away_team_id]||m.away_team_id)}<small class="fixture-extra">${live?'🔴 LIVE • ':''}${esc(m.match_date||'—')} • ${esc(m.venue||'—')}</small></div>`}).join('')||'<div class="empty">Hakuna mechi.</div>'}
function bindFixtureFilters(root=document){root.querySelectorAll('.fixture-filters').forEach(box=>{const buttons=[...box.querySelectorAll('button')];const rows=[...document.querySelectorAll(`.fixture-item[data-prefix="${box.dataset.prefix}"]`)];buttons.forEach(btn=>btn.onclick=()=>{buttons.forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter,today=new Date().toISOString().slice(0,10);rows.forEach(row=>{const d=row.dataset.date||'',played=row.dataset.played==='1';row.hidden=!(f==='all'||(f==='today'&&d===today)||(f==='upcoming'&&!played&&d>=today)||(f==='results'&&played))})})})}

function standingsTable(rows,names){const data=[...rows].sort((a,b)=>b.points-a.points||((b.goals_for-b.goals_against)-(a.goals_for-a.goals_against))||b.goals_for-a.goals_for||a.goals_against-b.goals_against||a.red_cards-b.red_cards||a.yellow_cards-b.yellow_cards);return `<div class="table-wrap"><table class="standings-table"><thead><tr><th>#</th><th>Timu</th><th>MP</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th><th>PTS</th></tr></thead><tbody>${data.map((x,i)=>{const gf=Number(x.goals_for)||0,ga=Number(x.goals_against)||0;return `<tr><td>${i+1}</td><td><a href="team.html?id=${encodeURIComponent(x.club_id)}">${esc(names[x.club_id]||x.club_id)}</a></td><td>${x.played||0}</td><td>${x.wins||0}</td><td>${x.draws||0}</td><td>${x.losses||0}</td><td>${gf}</td><td>${ga}</td><td>${gf-ga}</td><td><b>${x.points||0}</b></td></tr>`}).join('')}</tbody></table></div>`}
function leagueShell(title,sub,body){app.innerHTML=`<section class="competition-hero"><span class="eyebrow">AFRN LEAGUE CENTRE</span><h1>🏟️ ${esc(title)}</h1><p class="match-meta">${esc(sub)}</p></section><nav class="fm-tabs"><a href="#overview">Muhtasari</a><a href="#fixtures">Ratiba</a><a href="#standings">Msimamo</a><a href="#teams">Timu</a><a href="#scorers">Wafungaji</a><a href="#cards">Kadi</a><a href="#stats">Stats</a><a href="#history">Historia</a></nav>${body}`}
function playerName(p){return p?.name||p?.full_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||p?.player_name||p?.jina||p?.id||'Mchezaji'}
function eventKind(type){const t=String(type||'').toLowerCase().replace(/[- ]/g,'_');if(t==='goal'||t==='goal_scored'||t==='goal_scored_by_player'||t==='scored_goal')return 'goals';if(t==='assist'||t==='goal_assist'||t==='assist_goal'||t==='assists')return 'assists';if(t==='yellow'||t==='yellow_card'||t==='yellowcard')return 'yellow';if(t==='red'||t==='red_card'||t==='redcard')return 'red';return null}
function statRows(events,players,clubs,kind){const pm=Object.fromEntries(players.map(p=>[String(p.id),p]));const cm=Object.fromEntries(clubs.map(x=>[String(x.id),x]));const totals={};events.forEach(e=>{if(eventKind(e.event_type)!==kind||!e.player_id)return;const k=String(e.player_id);if(!totals[k])totals[k]={player_id:k,count:0,club_id:e.club_id};totals[k].count++});return Object.values(totals).sort((a,b)=>b.count-a.count||playerName(pm[a.player_id]).localeCompare(playerName(pm[b.player_id]))).map((x,i)=>`<div class="stat-row"><span class="stat-rank">${i+1}</span><a class="stat-player" href="player.html?id=${encodeURIComponent(x.player_id)}"><b>${esc(playerName(pm[x.player_id]))}</b><small>${esc(cm[x.club_id]?.name||'')}</small></a><strong class="stat-number">${x.count}</strong></div>`).join('')}
function statsPanel(events,players,clubs){const blocks=[['goals','⚽ Wafungaji','Hakuna mabao yaliyorekodiwa.'],['assists','🅰️ Assists','Hakuna assists zilizorekodiwa.'],['yellow','🟨 Yellow Cards','Hakuna kadi za njano zilizorekodiwa.'],['red','🟥 Red Cards','Hakuna kadi nyekundu zilizorekodiwa.']];return blocks.map(([kind,title,empty])=>{const rows=statRows(events,players,clubs,kind);return `<div class="stat-block"><div class="stat-block-head"><h3>${title}</h3><a href="scorers.html?competition=${encodeURIComponent(c?.name||'')}#${kind}">Angalia zote →</a></div>${rows||`<div class="empty">${empty}</div>`}</div>`}).join('')}
async function loadUpendo(){
 const [clubs,ct,st,matches,events,players]=await Promise.all([
  api('clubs?select=id,name,afrn_club_id,division,zone&order=name'),
  api(`competition_teams?competition_id=eq.${UPENDO_ID}&select=club_id,group_name,created_at&order=group_name,created_at`),
  api(`standings?competition_id=eq.${UPENDO_ID}&select=club_id,group_name,played,wins,draws,losses,goals_for,goals_against,points,yellow_cards,red_cards&order=group_name`),
  api(`matches?competition_id=eq.${UPENDO_ID}&select=id,home_team_id,away_team_id,match_date,match_time,venue,home_score,away_score,status,match_number,notes,home_penalties,away_penalties&order=match_number,match_date`),
  api(`match_events?match_id=in.(select%20id%20from%20matches%20where%20competition_id%20eq%20${UPENDO_ID})&select=id,match_id,player_id,club_id,event_type,minute,description`),
  api('players?select=*')
 ]);
 const names=Object.fromEntries(clubs.map(x=>[x.id,x.name]));
 const groups={};ct.forEach(x=>(groups[x.group_name]??=[]).push(x.club_id));
 const matchesHtml=matches.map(m=>`<tr><td>${m.match_number??'—'}</td><td colspan="2">${matchLink(m,names[m.home_team_id]||m.home_team_id,names[m.away_team_id]||m.away_team_id)}</td><td>${esc(m.match_date||'—')}</td><td>${esc(m.venue||'—')}</td><td>${esc(stage(m.notes))}</td></tr>`).join('');
 const ko=matches.filter(m=>/^(R16|QF|SF|THIRD|FINAL)/.test(stage(m.notes)));
 const koHtml=ko.length?ko.map(m=>`<tr><td>${esc(stage(m.notes))}</td><td colspan="2">${matchLink(m,names[m.home_team_id]||m.home_team_id,names[m.away_team_id]||m.away_team_id)}</td><td>${esc(m.status||'—')}</td></tr>`).join(''):'<tr><td colspan="4">Hakuna mechi za mtoano zilizorekodiwa.</td></tr>';
 const eventCounts=events.reduce((a,e)=>{const k=eventKind(e.event_type);if(k)a[k]=(a[k]||0)+1;return a},{});
 leagueShell('UPENDO WA WAKIMBIZI CUP','Msimu 2026 • AFRN • '+ct.length+' timu • Makundi A–F',`
 <section id="overview" class="card"><h2>🏆 Muhtasari wa Mashindano</h2><div class="cup-flow large">Makundi → Best Losers → Hatua ya 16 → Robo Fainali → Nusu Fainali → Mshindi wa 3 → Fainali</div><div class="quick-grid"><div><b>${ct.length}</b><span>Timu</span></div><div><b>${matches.length}</b><span>Mechi</span></div><div><b>${events.length}</b><span>Events</span></div><div><b>${Object.keys(groups).length}</b><span>Makundi</span></div></div></section>
 <section id="fixtures" class="card"><h2>📅 Ratiba & Matokeo</h2><div class="table-wrap"><table><thead><tr><th>#</th><th colspan="2">Mchezo</th><th>Tarehe</th><th>Uwanja</th><th>Hatua</th></tr></thead><tbody>${matchesHtml||'<tr><td colspan="6">Hakuna mechi.</td></tr>'}</tbody></table></div></section>
 <section id="standings" class="card"><h2>📊 Classement ya Makundi</h2>${Object.keys(groups).sort().map(g=>`<div class="group-title">GROUP ${esc(g)}</div>${standingsTable(st.filter(x=>x.group_name===g),names)}`).join('')}</section>
 <section id="teams" class="card"><h2>👥 Timu na Makundi</h2><div class="groups-grid">${Object.keys(groups).sort().map(g=>`<div class="group-card"><div class="group-header"><strong>GROUP ${esc(g)}</strong><span>${groups[g].length} timu</span></div><div class="group-body">${groups[g].map((clubId,i)=>teamLink(clubId,`${i+1}. ${names[clubId]||clubId}`,clubs.find(x=>String(x.id)===String(clubId))?.division||'')).join('')}</div></div>`).join('')}</div></section>
 <section class="card"><h2>🏆 Mtoano</h2><div class="knockout-grid"><div class="module"><b>BEST LOSERS</b></div><div class="module"><b>HATUA YA 16</b></div><div class="module"><b>ROBO FAINALI</b></div><div class="module"><b>NUSU FAINALI</b></div><div class="module"><b>MSHINDI WA 3</b></div><div class="module"><b>FAINALI</b></div></div><div class="table-wrap" style="margin-top:12px"><table><thead><tr><th>Hatua</th><th colspan="2">Mchezo</th><th>Status</th></tr></thead><tbody>${koHtml}</tbody></table></div></section>
 <section id="scorers" class="card"><h2>📊 Takwimu za Wachezaji</h2><p class="muted">Takwimu hizi zinatokana na events zilizorekodiwa kwenye mechi za Upendo wa Wakimbizi Cup pekee.</p><div class="stat-tabs"><a class="active" href="#scorers">Wafungaji</a><a href="#cards">Kadi</a><a href="scorers.html?competition=${encodeURIComponent('UPENDO WA WAKIMBIZI CUP')}">Centre ya Takwimu →</a></div><div class="stats-list">${statsPanel(events,players,clubs)}</div></section>
 <section id="cards" class="card"><h2>🟨 🟥 Kadi</h2><div class="quick-grid"><div><b>${eventCounts.yellow||0}</b><span>Yellow Cards</span></div><div><b>${eventCounts.red||0}</b><span>Red Cards</span></div><div><b>${eventCounts.goals||0}</b><span>Goals</span></div><div><b>${eventCounts.assists||0}</b><span>Assists</span></div></div><div class="stats-list">${statsPanel(events,players,clubs)}</div></section>
 <section id="stats" class="card"><h2>📈 Statistics</h2><div class="stats-list"><div><span>Mechi zilizorekodiwa</span><b>${matches.length}</b></div><div><span>Events zilizorekodiwa</span><b>${events.length}</b></div><div><span>Timu zilizosajiliwa</span><b>${ct.length}</b></div><div><span>Wafungaji wenye data</span><b>${Object.keys(events.filter(e=>eventKind(e.event_type)==='goals'&&e.player_id).reduce((a,e)=>(a[e.player_id]=1,a),{})).length}</b></div></div></section>
 <section id="history" class="card"><h2>📚 Historia</h2><p class="muted">Historia ya mashindano itaunganishwa na misimu na matokeo ya nyuma bila kuchanganya data ya mashindano mengine.</p></section>`);
}
async function loadLeague(){
 const teams=JSON.parse(localStorage.getItem('afrn_master_teams')||'[]').filter(t=>divisionOf(c)==='Open'||t.division===c.division);
 let matches=[],events=[],players=[],clubs=[];
 if(c.sourceCompetitionId){
  matches=await api(`matches?competition_id=eq.${c.sourceCompetitionId}&select=id,home_team_id,away_team_id,match_date,match_time,venue,home_score,away_score,status,notes&order=match_date,match_time`);
  players=await api('players?select=*'); clubs=await api('clubs?select=id,name');
  const mids=matches.map(m=>m.id);
  if(mids.length) events=await api(`match_events?match_id=in.(${mids.join(',')})&select=id,match_id,player_id,club_id,event_type,minute,description`);
 }
 const names={...Object.fromEntries(teams.map(t=>[String(t.id),t.jina||t.name])),...Object.fromEntries(clubs.map(x=>[String(x.id),x.name]))};
 const rows=c.sourceCompetitionId?aggregateStandings(matches,teams.map(t=>String(t.id))):teams.map(t=>({club_id:t.id,played:t.P||0,wins:t.W||0,draws:t.D||0,losses:t.L||0,goals_for:t.GF||0,goals_against:t.GA||0,points:t.Pts||0,yellow_cards:0,red_cards:0}));
 const table=rows.length?standingsTable(rows,names):'<div class="empty">Hakuna timu iliyosajiliwa katika daraja hili bado.</div>';
 const goals=events.filter(e=>eventKind(e.event_type)==='goals').length;
 const yellows=events.filter(e=>eventKind(e.event_type)==='yellow').length;
 const liveStats=c.sourceCompetitionId?statsPanel(events,players,clubs):'<div class="empty">Hakuna data ya wafungaji/kadi bado.</div>';
 leagueShell(c.name,`Msimu ${c.season} • ${c.division}`,`
 <section id="overview" class="card"><h2>🏆 Muhtasari</h2><div class="quick-grid"><div><b>${teams.length}</b><span>Timu</span></div><div><b>${matches.length}</b><span>Mechi</span></div><div><b>${goals}</b><span>Mabao</span></div><div><b>${yellows}</b><span>Kadi</span></div></div><div class="info">Data ya ligi inaonyesha timu za <b>${esc(c.division)}</b> pekee. Matokeo na msimamo hutokana na mechi zilizorekodiwa.</div></section>
 <section id="fixtures" class="card"><h2>📅 Ratiba & Matokeo</h2><div class="fixture-filters" data-prefix="league"><button class="active" data-filter="all">Zote</button><button data-filter="today">Leo</button><button data-filter="upcoming">Upcoming</button><button data-filter="results">Results</button></div><div class="fixture-list">${fixtureRows(matches,names,'league')}</div></section>
 <section id="standings" class="card"><h2>📊 Msimamo</h2>${table}</section>
 <section id="teams" class="card"><h2>👥 Timu</h2><div class="team-grid">${teams.map(t=>teamLink(t.id,t.jina||t.name,`${t.division}${t.zone?' • '+t.zone:''}`)).join('')||'<div class="empty">Hakuna timu.</div>'}</div></section>
 <section id="scorers" class="card"><h2>⚽ Wafungaji</h2>${liveStats}</section>
 <section id="cards" class="card"><h2>🟨 🟥 Kadi</h2>${liveStats}</section>
 <section id="stats" class="card"><h2>📈 Statistics</h2><div class="empty">${c.sourceCompetitionId?'Takwimu za kina zitaonekana hapa kadri match_statistics zinavyorekodiwa.':'Statistics zitaongezeka kadri mechi zinavyorekodiwa.'}</div></section>
 <section id="history" class="card"><h2>📚 Historia</h2><div class="empty">Historia ya ${esc(c.name)} itawekwa hapa.</div></section>`);
 bindFixtureFilters();
}
function divisionOf(l){return l?.division||l?.name||''}
async function render(){if(!c){app.innerHTML='<div class="empty">Mashindano hayajapatikana.</div>';return}if(c.source==='supabase'||String(c.name).toLowerCase().includes('upendo')){try{await loadUpendo()}catch(e){app.innerHTML=`<div class="empty">❌ Imeshindikana kuonyesha data ya Upendo wa Wakimbizi Cup.<br>${esc(e.message)}</div>`}return}await loadLeague()}
render();
