const leagues=JSON.parse(localStorage.getItem('afrn_leagues')||'[]');
const id=Number(new URLSearchParams(location.search).get('id'));
const c=leagues[id];
const app=document.getElementById('app');
const SUPABASE_URL='https://jjqhvruppafpumcthmwe.supabase.co';
const SUPABASE_KEY='sb_publishable_02hhRG8bgDOqSFxva8IMvQ_zWTLMa3G';
const UPENDO_ID='3b55884e-05bc-4d83-832e-3addcd97d970';
function esc(s){return String(s??'').replace(/[&<>\"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[x]))}
async function api(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY}});if(!r.ok)throw new Error('Supabase: '+r.status);return r.json()}
function score(m){if(m.home_score==null||m.away_score==null)return '—';return `${m.home_score} - ${m.away_score}`}
function stage(notes=''){const m=String(notes);const x=m.match(/AFRN_STAGE=([^|]+)/);if(x)return x[1];for(const g of ['A','B','C','D','E','F'])if(m.includes('Group '+g))return 'GROUP '+g;return 'GROUP STAGE'}
function teamLink(id,name,meta=''){return `<a class="team-link-card" href="team.html?id=${encodeURIComponent(id)}"><b>${esc(name)}</b><small>${esc(meta)}</small></a>`}
function matchLink(m,home,away){return `<a class="match-row-link" href="match.html?id=${encodeURIComponent(m.id)}"><span>${esc(home)}</span><b>${score(m)}</b><span>${esc(away)}</span></a>`}
function standingsTable(rows,names){const data=[...rows].sort((a,b)=>b.points-a.points||((b.goals_for-b.goals_against)-(a.goals_for-a.goals_against))||b.goals_for-a.goals_for||a.goals_against-b.goals_against||a.red_cards-b.red_cards||a.yellow_cards-b.yellow_cards);return `<div class="table-wrap"><table class="standings-table"><thead><tr><th>#</th><th>Timu</th><th>P</th><th>GF</th><th>GA</th><th>Pts</th></tr></thead><tbody>${data.map((x,i)=>`<tr><td>${i+1}</td><td><a href="team.html?id=${encodeURIComponent(x.club_id)}">${esc(names[x.club_id]||x.club_id)}</a></td><td>${x.played||0}</td><td>${x.goals_for||0}</td><td>${x.goals_against||0}</td><td><b>${x.points||0}</b></td></tr>`).join('')}</tbody></table></div>`}
function leagueShell(title,sub,body){app.innerHTML=`<section class="competition-hero"><span class="eyebrow">AFRN LEAGUE CENTRE</span><h1>🏟️ ${esc(title)}</h1><p class="match-meta">${esc(sub)}</p></section><nav class="fm-tabs"><a href="#overview">Muhtasari</a><a href="#fixtures">Ratiba</a><a href="#standings">Msimamo</a><a href="#teams">Timu</a><a href="#scorers">Wafungaji</a><a href="#cards">Kadi</a><a href="#stats">Stats</a><a href="#history">Historia</a></nav>${body}`}
async function loadUpendo(){
 const [clubs,ct,st,matches,events]=await Promise.all([
  api('clubs?select=id,name,afrn_club_id,division,zone&order=name'),
  api(`competition_teams?competition_id=eq.${UPENDO_ID}&select=club_id,group_name,created_at&order=group_name,created_at`),
  api(`standings?competition_id=eq.${UPENDO_ID}&select=club_id,group_name,played,wins,draws,losses,goals_for,goals_against,points,yellow_cards,red_cards&order=group_name`),
  api(`matches?competition_id=eq.${UPENDO_ID}&select=id,home_team_id,away_team_id,match_date,match_time,venue,home_score,away_score,status,match_number,notes,home_penalties,away_penalties&order=match_number,match_date`),
  api(`match_events?match_id=in.(select%20id%20from%20matches%20where%20competition_id%20eq%20${UPENDO_ID})&select=id,match_id,player_id,club_id,event_type,minute,description`)
 ]);
 const names=Object.fromEntries(clubs.map(x=>[x.id,x.name]));
 const groups={};ct.forEach(x=>(groups[x.group_name]??=[]).push(x.club_id));
 const matchesHtml=matches.map(m=>`<tr><td>${m.match_number??'—'}</td><td colspan="2">${matchLink(m,names[m.home_team_id]||m.home_team_id,names[m.away_team_id]||m.away_team_id)}</td><td>${esc(m.match_date||'—')}</td><td>${esc(m.venue||'—')}</td><td>${esc(stage(m.notes))}</td></tr>`).join('');
 const ko=matches.filter(m=>/^(R16|QF|SF|THIRD|FINAL|GROUP)/.test(stage(m.notes))&&/AFRN_STAGE/.test(m.notes||''));
 const koHtml=ko.length?ko.map(m=>`<tr><td>${esc(stage(m.notes))}</td><td colspan="2">${matchLink(m,names[m.home_team_id]||m.home_team_id,names[m.away_team_id]||m.away_team_id)}</td><td>${esc(m.status||'—')}</td></tr>`).join(''):'<tr><td colspan="4">Hakuna mechi za mtoano zilizorekodiwa.</td></tr>';
 const eventCounts=events.reduce((a,e)=>{const k=String(e.event_type||'other').toLowerCase();a[k]=(a[k]||0)+1;return a},{});
 leagueShell('UPENDO WA WAKIMBIZI CUP','Msimu 2026 • AFRN • '+ct.length+' timu • Makundi A–F',`
 <section id="overview" class="card"><h2>🏆 Muhtasari wa Mashindano</h2><div class="cup-flow large">Makundi → Best Losers → Hatua ya 16 → Robo Fainali → Nusu Fainali → Mshindi wa 3 → Fainali</div><div class="quick-grid"><div><b>${ct.length}</b><span>Timu</span></div><div><b>${matches.length}</b><span>Mechi</span></div><div><b>${events.length}</b><span>Events</span></div><div><b>${Object.keys(groups).length}</b><span>Makundi</span></div></div></section>
 <section id="fixtures" class="card"><h2>📅 Ratiba & Matokeo</h2><div class="table-wrap"><table><thead><tr><th>#</th><th colspan="2">Mchezo</th><th>Tarehe</th><th>Uwanja</th><th>Hatua</th></tr></thead><tbody>${matchesHtml||'<tr><td colspan="6">Hakuna mechi.</td></tr>'}</tbody></table></div></section>
 <section id="standings" class="card"><h2>📊 Classement ya Makundi</h2>${Object.keys(groups).sort().map(g=>`<div class="group-title">GROUP ${esc(g)}</div>${standingsTable(st.filter(x=>x.group_name===g),names)}`).join('')}</section>
 <section id="teams" class="card"><h2>👥 Timu na Makundi</h2><div class="groups-grid">${Object.keys(groups).sort().map(g=>`<div class="group-card"><div class="group-header"><strong>GROUP ${esc(g)}</strong><span>${groups[g].length} timu</span></div><div class="group-body">${groups[g].map((clubId,i)=>teamLink(clubId,`${i+1}. ${names[clubId]||clubId}`,clubs.find(x=>String(x.id)===String(clubId))?.division||'')).join('')}</div></div>`).join('')}</div></section>
 <section class="card"><h2>🏆 Mtoano</h2><div class="knockout-grid"><div class="module"><b>BEST LOSERS</b></div><div class="module"><b>HATUA YA 16</b></div><div class="module"><b>ROBO FAINALI</b></div><div class="module"><b>NUSU FAINALI</b></div><div class="module"><b>MSHINDI WA 3</b></div><div class="module"><b>FAINALI</b></div></div><div class="table-wrap" style="margin-top:12px"><table><thead><tr><th>Hatua</th><th colspan="2">Mchezo</th><th>Status</th></tr></thead><tbody>${koHtml}</tbody></table></div></section>
 <section id="scorers" class="card"><h2>⚽ Wafungaji</h2><p class="muted">Tukio la bao linahifadhiwa kwenye Match Centre. Orodha ya wafungaji itajengwa kutoka player_id za events.</p></section>
 <section id="cards" class="card"><h2>🟨 🟥 Kadi</h2><div class="quick-grid"><div><b>${eventCounts.yellow_card||eventCounts.yellow||0}</b><span>Yellow</span></div><div><b>${eventCounts.red_card||eventCounts.red||0}</b><span>Red</span></div><div><b>${eventCounts.goal||0}</b><span>Goals</span></div><div><b>${events.length}</b><span>Events zote</span></div></div></section>
 <section id="stats" class="card"><h2>📈 Statistics</h2><div class="stats-list"><div><span>Mechi zilizorekodiwa</span><b>${matches.length}</b></div><div><span>Events zilizorekodiwa</span><b>${events.length}</b></div><div><span>Timu zilizosajiliwa</span><b>${ct.length}</b></div></div></section>
 <section id="history" class="card"><h2>📚 Historia</h2><p class="muted">Historia ya mashindano itaunganishwa na misimu na matokeo ya nyuma bila kuchanganya data ya mashindano mengine.</p></section>`);
}
function loadLeague(){
 const teams=JSON.parse(localStorage.getItem('afrn_master_teams')||'[]').filter(t=>divisionOf(c)==='Open'||t.division===c.division);
 const sorted=[...teams].sort((a,b)=>(b.Pts||0)-(a.Pts||0)||((b.GF||0)-(b.GA||0))-((a.GF||0)-(a.GA||0))||(b.GF||0)-(a.GF||0));
 const table=sorted.length?`<div class="table-wrap"><table><thead><tr><th>#</th><th>Timu</th><th>P</th><th>GF</th><th>GA</th><th>Pts</th></tr></thead><tbody>${sorted.map((t,i)=>`<tr><td>${i+1}</td><td><a href="team.html?id=${encodeURIComponent(t.id)}">${esc(t.jina)}</a></td><td>${t.P||0}</td><td>${t.GF||0}</td><td>${t.GA||0}</td><td><b>${t.Pts||0}</b></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Hakuna timu iliyosajiliwa katika daraja hili bado.</div>';
 leagueShell(c.name,`Msimu ${c.season} • ${c.division}`,`<section id="overview" class="card"><h2>🏆 Muhtasari wa Ligi</h2><div class="quick-grid"><div><b>${teams.length}</b><span>Timu za ${esc(c.division)}</span></div><div><b>0</b><span>Mechi</span></div><div><b>0</b><span>Wafungaji</span></div><div><b>0</b><span>Kadi</span></div></div><div class="info">Mfumo huu hauchanganyi timu: ligi ya <b>${esc(c.division)}</b> inaonyesha timu za daraja hilo pekee.</div></section><section id="fixtures" class="card"><h2>📅 Ratiba & Matokeo</h2><div class="empty">Ratiba itaonekana hapa baada ya mechi kusajiliwa.</div></section><section id="standings" class="card"><h2>📊 Msimamo</h2>${table}</section><section id="teams" class="card"><h2>👥 Timu</h2><div class="team-grid">${teams.map(t=>teamLink(t.id,t.jina,`${t.division}${t.zone?' • '+t.zone:''}`)).join('')||'<div class="empty">Hakuna timu.</div>'}</div></section><section id="scorers" class="card"><h2>⚽ Wafungaji</h2><div class="empty">Hakuna takwimu za wafungaji bado.</div></section><section id="cards" class="card"><h2>🟨 🟥 Kadi</h2><div class="empty">Hakuna kadi zilizorekodiwa bado.</div></section><section id="stats" class="card"><h2>📈 Statistics</h2><div class="empty">Statistics zitaongezeka kadri mechi zinavyorekodiwa.</div></section><section id="history" class="card"><h2>📚 Historia</h2><div class="empty">Historia ya ${esc(c.name)} itawekwa hapa.</div></section>`)
}
function divisionOf(l){return l?.division||l?.name||''}
async function render(){if(!c){app.innerHTML='<div class="empty">Mashindano hayajapatikana.</div>';return}if(c.source==='supabase'||String(c.name).toLowerCase().includes('upendo')){try{await loadUpendo()}catch(e){app.innerHTML=`<div class="empty">❌ Imeshindikana kuonyesha data ya Upendo wa Wakimbizi Cup.<br>${esc(e.message)}</div>`}return}loadLeague()}
render();
