const AFRN_SHOTS_URL='https://jjqhvruppafpumcthmwe.supabase.co';
const AFRN_SHOTS_KEY='sb_publishable_02hhRG8bgDOqSFxva8IMvQ_zWTLMa3G';
const AFRN_SHOT_MATCH_ID=new URLSearchParams(location.search).get('id');
let afrnShots=[];
const shotLabels={goal:'⚽ Goal',on_target:'🎯 On target',off_target:'❌ Off target',blocked:'🧱 Blocked'};
function shotEsc(v){return String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]))}
async function loadShots(){
 if(!AFRN_SHOT_MATCH_ID)return [];
 const url=`${AFRN_SHOTS_URL}/rest/v1/match_shots?match_id=eq.${encodeURIComponent(AFRN_SHOT_MATCH_ID)}&select=id,team_side,player_id,minute,period,shot_type,x,y,xg,description&order=minute.asc.nullslast,created_at.asc`;
 const r=await fetch(url,{headers:{apikey:AFRN_SHOTS_KEY,Authorization:'Bearer '+AFRN_SHOTS_KEY}});if(!r.ok)throw Error('Shots '+r.status);return await r.json();
}
function pitchDot(s,idx){const x=Math.max(0,Math.min(100,Number(s.x)||0)),y=Math.max(0,Math.min(100,Number(s.y)||0));return `<button class="afrn-shot-dot ${s.team_side==='away'?'away':''} ${s.shot_type==='goal'?'goal':''}" style="left:${x}%;top:${y}%" title="${shotEsc(shotLabels[s.shot_type]||s.shot_type)}" onclick="showShotInfo(${idx})">${s.shot_type==='goal'?'⚽':'•'}</button>`}
function renderShotMap(){const target=document.getElementById('shotMap');if(!target)return;if(!afrnShots.length){target.innerHTML='<div class="section-head"><h2>🎯 Shot Map</h2><button class="afrn-edit-stats" onclick="openShotEditor()">✏️ Ingiza Shots</button></div><div class="empty">Hakuna shots zilizorekodiwa bado.</div>';return}
 const home=afrnShots.filter(s=>s.team_side==='home').length,away=afrnShots.length-home;
 target.innerHTML=`<div class="section-head"><h2>🎯 Shot Map</h2><div><span class="event-count">${home} NYUMBANI • ${away} UGENINI</span><button class="afrn-edit-stats" onclick="openShotEditor()">✏️ Ingiza</button></div></div><div class="afrn-pitch"><div class="afrn-pitch-mid"></div><div class="afrn-pitch-box home-box"></div><div class="afrn-pitch-box away-box"></div>${afrnShots.map(pitchDot).join('')}</div><div id="afrn-shot-info" class="afrn-shot-info">Gusa alama kuona taarifa ya shuti.</div>`;
}
function showShotInfo(i){const s=afrnShots[i],box=document.getElementById('afrn-shot-info');if(!box||!s)return;box.innerHTML=`<b>${s.team_side==='home'?'NYUMBANI':'UGENINI'}</b> • ${shotEsc(shotLabels[s.shot_type]||s.shot_type)}${s.minute!==null?' • '+shotEsc(s.minute)+"'":''}${s.xg!==null&&s.xg!==undefined?' • xG '+Number(s.xg).toFixed(2):''}${s.description?' • '+shotEsc(s.description):''}`}
function shotInput(name,label,type='number',step='1'){return `<label>${label}<input id="shot-${name}" type="${type}" step="${step}" ${type==='number'?'min="0"':''}></label>`}
function openShotEditor(){const target=document.getElementById('shotMap');if(!target)return;target.innerHTML=`<div class="section-head"><h2>✏️ Ingiza Shuti</h2><span class="event-count">SHOT MAP</span></div><div class="afrn-shot-form"><label>Timu<select id="shot-side"><option value="home">NYUMBANI</option><option value="away">UGENINI</option></select></label><label>Aina ya shuti<select id="shot-type"><option value="goal">Goal</option><option value="on_target">On target</option><option value="off_target">Off target</option><option value="blocked">Blocked</option></select></label>${shotInput('minute','Dakika')}${shotInput('x','X (0–100)')}${shotInput('y','Y (0–100)')}${shotInput('xg','xG','number','0.01')}<label>Maelezo<input id="shot-description" type="text" placeholder="Mfano: shuti la mbali"></label></div><div id="shot-save-msg" class="afrn-save-msg"></div><div class="afrn-edit-actions"><button class="afrn-cancel-stats" onclick="refreshShots()">✕ Ghairi</button><button class="afrn-save-stats" onclick="saveShot()">💾 Hifadhi Shuti</button></div><div class="afrn-shot-list">${afrnShots.map((s,i)=>`<div><b>${s.team_side==='home'?'N':'U'}</b> ${s.minute??'—'}' — ${shotEsc(shotLabels[s.shot_type]||s.shot_type)} <button onclick="deleteShot('${shotEsc(s.id)}')">🗑️</button></div>`).join('')}</div>`}
async function saveShot(){const msg=document.getElementById('shot-save-msg');const x=Number(document.getElementById('shot-x').value),y=Number(document.getElementById('shot-y').value),xg=document.getElementById('shot-xg').value;const minute=document.getElementById('shot-minute').value; if(!Number.isFinite(x)||x<0||x>100||!Number.isFinite(y)||y<0||y>100){msg.textContent='❌ X na Y lazima ziwe kati ya 0–100.';msg.className='afrn-save-msg error';return} if(xg!==''&&Number(xg)<0){msg.textContent='❌ xG haiwezi kuwa chini ya 0.';msg.className='afrn-save-msg error';return}msg.textContent='⏳ Inahifadhi...';try{const body={match_id:AFRN_SHOT_MATCH_ID,team_side:document.getElementById('shot-side').value,shot_type:document.getElementById('shot-type').value,x,y,xg:xg===''?null:Number(xg),minute:minute===''?null:Number(minute),description:document.getElementById('shot-description').value||null};const r=await fetch(`${AFRN_SHOTS_URL}/rest/v1/match_shots`,{method:'POST',headers:{apikey:AFRN_SHOTS_KEY,Authorization:'Bearer '+AFRN_SHOTS_KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());msg.textContent='✅ Shuti limehifadhiwa.';setTimeout(refreshShots,500)}catch(e){msg.textContent='❌ '+String(e.message||e);msg.className='afrn-save-msg error'}}
async function deleteShot(id){if(!confirm('Futa shuti hili?'))return;const r=await fetch(`${AFRN_SHOTS_URL}/rest/v1/match_shots?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{apikey:AFRN_SHOTS_KEY,Authorization:'Bearer '+AFRN_SHOTS_KEY}});if(r.ok)refreshShots();else alert('Imeshindikana kufuta shuti.')}
async function refreshShots(){try{afrnShots=await loadShots();renderShotMap()}catch(e){console.warn('AFRN shot map:',e)}}
refreshShots();setInterval(refreshShots,15000);