const SUPABASE_URL='https://jjqhvruppafpumcthmwe.supabase.co';
const SUPABASE_KEY='sb_publishable_02hhRG8bgDOqSFxva8IMvQ_zWTLMa3G';
const matchId=new URLSearchParams(location.search).get('id');
const box=document.getElementById('matchApp');
let liveChannel=null,refreshTimer=null,lastRendered='',realtimeState='connecting';
function esc(s){return String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]))}
async function api(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY}});if(!r.ok)throw Error('Supabase '+r.status);return r.json()}
function type(e){return String(e.event_type||'').toLowerCase().trim().replace(/[\s-]+/g,'_')}
function playerName(p){return p?.full_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||('Mchezaji #'+(p?.shirt_number||''))}
function eventInfo(e){const x=type(e),d=String(e.description||'').trim();if(['goal','goals','goal_scored'].includes(x))return {icon:'⚽',label:'GOAL',kind:'goal'};if(['own_goal','own-goal'].includes(x))return {icon:'⚽',label:'OWN GOAL',kind:'own'};if(['assist','assist_goal','goal_assist'].includes(x))return {icon:'🅰️',label:'ASSIST',kind:'assist'};if(['yellow_card','yellow'].includes(x))return {icon:'🟨',label:'YELLOW CARD',kind:'yellow'};if(['red_card','red'].includes(x))return {icon:'🟥',label:'RED CARD',kind:'red'};if(['substitution','sub','sub_in','sub_out'].includes(x)||x.includes('substitution'))return {icon:'🔄',label:'SUBSTITUTION',kind:'sub'};if(x.includes('var'))return {icon:'📺',label:'VAR',kind:'var'};if(['penalty','penalty_goal'].includes(x))return {icon:'⚽',label:'PENALTY',kind:'penalty'};return {icon:'•',label:d||e.event_type||'EVENT',kind:'other'}}
function minute(e){return e.minute===null||e.minute===undefined||e.minute===''?'—':`${esc(e.minute)}’`}
function eventDetail(e,info,p){const d=String(e.description||'').trim();if(d)return d;if(p&&(info.kind==='goal'||info.kind==='own'||info.kind==='penalty'||info.kind==='assist'))return playerName(p);if(p)return playerName(p);return ''}
function eventPlayer(e,info,p){if(!p)return '';const label=['goal','own','penalty'].includes(info.kind)?'Mfungaji':info.kind==='assist'?'Assist':'Mchezaji';return `<a href="player.html?id=${encodeURIComponent(p.id)}">${esc(playerName(p))}</a><small>${label}</small>`}
function eventHtml(e,byPlayer,names){const info=eventInfo(e),p=byPlayer[e.player_id],detail=eventDetail(e,info,p),team=names[e.club_id]||'Timu';return `<article class="live-event ${info.kind}"><div class="event-minute">${minute(e)}</div><div class="event-symbol">${info.icon}</div><div class="event-body"><strong>${esc(info.label)}</strong>${eventPlayer(e,info,p)}${detail&&detail!==playerName(p)?`<small>${esc(detail)}</small>`:''}</div><div class="event-team">${esc(team)}</div></article>`}
function lineup(clubId,events,byPlayer,teamLabel){const starters=events.filter(e=>String(e.club_id)===String(clubId)&&['starting_xi','starter','lineup_start','starting','starting11','lineup'].includes(type(e))).map(e=>byPlayer[e.player_id]).filter(Boolean);const subs=events.filter(e=>String(e.club_id)===String(clubId)&&['substitute','bench','sub','substitution'].includes(type(e))).map(e=>byPlayer[e.player_id]).filter(Boolean);const list=(arr,empty)=>arr.length?`<div class="player-list">${arr.map(p=>`<a class="club-row" href="player.html?id=${encodeURIComponent(p.id)}"><span>${p.shirt_number?`#${esc(p.shirt_number)} `:''}${esc(playerName(p))}</span><small>${esc(p.position||'')}</small></a>`).join('')}</div>`:`<div class="empty">${empty}</div>`;return `<div class="lineup-side"><h3>${esc(teamLabel(clubId))}</h3><h4>Starting XI</h4>${list(starters,'Starting XI haijawekwa.')}<h4>Substitutes</h4>${list(subs,'Substitutes hawajawekwa.')}</div>`}
function count(arr,keys){return arr.filter(e=>keys.includes(type(e))).length}
function setRealtimeState(s){realtimeState=s;const el=document.getElementById('realtimeState');if(el){el.className='realtime-state '+s;el.textContent=s==='connected'?'🟢 LIVE CONNECTION':s==='connecting'?'🟡 Inaunganisha…':'🟠 Fallback: refresh 15s'}}
async function render(){
 if(!matchId){box.innerHTML='<div class="empty">Mechi haijachaguliwa.</div>';return}
 const [matches,clubs,events,players]=await Promise.all([
  api(`matches?id=eq.${encodeURIComponent(matchId)}&select=id,competition_id,home_team_id,away_team_id,match_date,match_time,venue,home_score,away_score,status,match_number,notes,home_penalties,away_penalties`),
  api('clubs?select=id,name,short_name,afrn_club_id,logo_url,division,zone'),
  api(`match_events?match_id=eq.${encodeURIComponent(matchId)}&select=id,player_id,club_id,event_type,minute,description&order=minute,id`),
  api('players?select=id,first_name,last_name,full_name,shirt_number,position,club_id')
 ]);
 if(!matches.length){box.innerHTML='<div class="empty">Mechi haijapatikana.</div>';return}
 const m=matches[0],names=Object.fromEntries(clubs.map(c=>[c.id,c.name||c.short_name])),byPlayer=Object.fromEntries(players.map(p=>[p.id,p]));
 const teamLabel=id=>names[id]||'Timu';
 const homeEvents=events.filter(e=>String(e.club_id)===String(m.home_team_id)),awayEvents=events.filter(e=>String(e.club_id)===String(m.away_team_id));
 const score=m.home_score==null?'—':`${m.home_score} - ${m.away_score}`;
 const live=['LIVE','IN_PLAY','1H','2H','HT','ET','PAUSED'].includes(String(m.status||'').toUpperCase());
 const status=String(m.status||'').toUpperCase()||(live?'LIVE':'');
 const ev=events.map(e=>eventHtml(e,byPlayer,names)).join('');
 const key=JSON.stringify([m.home_score,m.away_score,m.status,m.notes,events.map(e=>[e.id,e.event_type,e.minute,e.description,e.player_id,e.club_id])]);
 if(key===lastRendered)return;lastRendered=key;
 const updated=new Date().toLocaleTimeString('sw-TZ',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
 box.innerHTML=`<section class="match-hero"><div class="match-meta">${esc(m.match_date||'Tarehe haijawekwa')} ${m.match_time?'• '+esc(m.match_time):''} ${m.venue?'• '+esc(m.venue):''}</div><div class="live-row">${live?'<div class="live-pill">🔴 LIVE — Inasasishwa moja kwa moja</div>':''}<div id="realtimeState" class="realtime-state ${realtimeState}">${realtimeState==='connected'?'🟢 LIVE CONNECTION':realtimeState==='connecting'?'🟡 Inaunganisha…':'🟠 Fallback: refresh 15s'}</div></div><div class="match-teams"><div><div class="crest">⚽</div><h2>${esc(teamLabel(m.home_team_id))}</h2><small>NYUMBANI</small></div><div class="big-score"><strong>${score}</strong><span>${esc(status||'MATOKEO')}</span>${m.home_penalties!=null||m.away_penalties!=null?`<small>Penalti: ${esc(m.home_penalties??0)} - ${esc(m.away_penalties??0)}</small>`:''}</div><div><div class="crest">⚽</div><h2>${esc(teamLabel(m.away_team_id))}</h2><small>UGENINI</small></div></div></section>
 <nav class="match-tabs"><a href="#overview">Muhtasari</a><a href="#events">Matukio</a><a href="#lineups">Lineups</a><a href="#stats">Takwimu</a></nav>
 <section id="overview" class="card"><h2>📋 Muhtasari wa Mchezo</h2><div class="quick-grid"><div><b>🏟️ Uwanja</b><span>${esc(m.venue||'—')}</span></div><div><b>📅 Tarehe</b><span>${esc(m.match_date||'—')}</span></div><div><b>⏱️ Muda</b><span>${esc(m.match_time||'—')}</span></div><div><b>🔢 Mechi</b><span>${esc(m.match_number??'—')}</span></div></div>${m.notes?`<div class="match-note"><b>📝 Commentary</b><span>${esc(m.notes)}</span></div>`:''}<div class="updated-at">Imeboreshwa: ${esc(updated)}</div></section>
 <section id="events" class="card"><div class="section-head"><h2>⏱️ Matukio ya Mchezo</h2><span class="event-count">${events.length} events</span></div>${ev||'<div class="empty">Hakuna matukio yaliyorekodiwa.</div>'}</section>
 <section id="lineups" class="card"><h2>👥 Lineups</h2><div class="lineups-grid">${lineup(m.home_team_id,events,byPlayer,teamLabel)}${lineup(m.away_team_id,events,byPlayer,teamLabel)}</div></section>
 <section id="stats" class="card"><h2>📊 Takwimu za Mchezo</h2><div class="stats-list"><div><span>⚽ Goals</span><b>${count(homeEvents,['goal','goals','goal_scored'])} — ${count(awayEvents,['goal','goals','goal_scored'])}</b></div><div><span>🟨 Yellow Cards</span><b>${count(homeEvents,['yellow_card','yellow'])} — ${count(awayEvents,['yellow_card','yellow'])}</b></div><div><span>🟥 Red Cards</span><b>${count(homeEvents,['red_card','red'])} — ${count(awayEvents,['red_card','red'])}</b></div><div><span>⏱️ Matukio</span><b>${events.length}</b></div><div><span>🔄 Substitutions</span><b>${count(homeEvents,['substitution','sub','sub_in','sub_out'])} — ${count(awayEvents,['substitution','sub','sub_in','sub_out'])}</b></div></div><p class="muted">Possession, shots, corners, xG na takwimu nyingine zitaonekana hapa tu pale zinaporekodiwa kwenye mfumo.</p></section>`;
}
function startLive(){if(!matchId||!window.supabase){setRealtimeState('fallback');return}try{const client=window.supabase;liveChannel=client.channel('afrn-live-match-'+matchId).on('postgres_changes',{event:'*',schema:'public',table:'matches',filter:'id=eq.'+matchId},()=>render().catch(console.warn)).on('postgres_changes',{event:'*',schema:'public',table:'match_events',filter:'match_id=eq.'+matchId},()=>render().catch(console.warn)).subscribe((s)=>{if(s==='SUBSCRIBED')setRealtimeState('connected');else if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(s))setRealtimeState('fallback')});}catch(e){console.warn('Realtime:',e);setRealtimeState('fallback')}clearInterval(refreshTimer);refreshTimer=setInterval(()=>render().catch(console.warn),15000)}
function cleanup(){clearInterval(refreshTimer);if(liveChannel&&window.supabase)window.supabase.removeChannel(liveChannel)}
window.addEventListener('beforeunload',cleanup);
render().then(startLive).catch(e=>{box.innerHTML=`<div class="empty">❌ ${esc(e.message)}</div>`});