const SUPABASE_URL='https://jjqhvruppafpumcthmwe.supabase.co';
const SUPABASE_KEY='sb_publishable_02hhRG8bgDOqSFxva8IMvQ_zWTLMa3G';
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`};const $=id=>document.getElementById(id);
let allRows=[],clubs=[],players=[],matches=[],competitions=[],shots=[];
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function api(table,params=''){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${params}`,{headers});if(!r.ok)throw new Error(`${table}: ${r.status}`);return r.json();}
function norm(v){return String(v||'').toLowerCase().replace(/[-\s]/g,'_');}
function eventStat(type){const t=norm(type);if(t.includes('own_goal'))return null;if(t.includes('yellow'))return'yellow';if(t.includes('red'))return'red';if(t==='goal'||t==='goals'||t==='goal_scored')return'goals';if(t.includes('assist'))return'assists';return null;}
function playerName(id){const p=players.find(x=>String(x.id)===String(id));return p?.name||p?.full_name||p?.jina||`Player ${id}`;}
function clubName(id){const c=clubs.find(x=>String(x.id)===String(id));return c?.name||c?.short_name||`Team ${id}`;}
function competitionName(m){const c=competitions.find(x=>String(x.id)===String(m?.competition_id));return c?.name||c?.title||m?.competition||'';}
function selectedCompetition(){const params=new URLSearchParams(location.search);return params.get('competition')||params.get('competition_id')||'';}
function competitionMatches(){const f=$('competitionFilter').value;return f==='all'?matches:matches.filter(m=>String(m?.competition_id)===f);}
function populateCompetitionFilter(){const f=$('competitionFilter');const current=selectedCompetition()||f.value;const list=[...competitions].sort((a,b)=>String(a.name||a.title||'').localeCompare(String(b.name||b.title||'')));f.innerHTML='<option value="all">Mashindano yote</option>'+list.map(c=>`<option value="${esc(c.id)}">${esc(c.name||c.title||'Competition')}</option>`).join('');if(current&&[...f.options].some(o=>o.value===current))f.value=current;}
function aggregate(){const allowed=new Set(competitionMatches().map(m=>String(m.id)));const map=new Map();const ensure=(id,clubId)=>{const key=String(id);if(!map.has(key))map.set(key,{id:key,name:playerName(id),team:clubName(clubId),clubId,goals:0,assists:0,yellow:0,red:0,shots:0,on_target:0,appearances:new Set()});const x=map.get(key);if(!x.clubId&&clubId)x.clubId=clubId;if(x.team.startsWith('Team ')&&clubId)x.team=clubName(clubId);return x};for(const e of allRows){if(!allowed.has(String(e.match_id))||!e.player_id)continue;const s=eventStat(e.event_type);if(s){const x=ensure(e.player_id,e.club_id);x[s]++;x.appearances.add(String(e.match_id));}}for(const s of shots){if(!allowed.has(String(s.match_id))||!s.player_id)continue;const x=ensure(s.player_id,null);x.shots++;if(s.shot_type==='goal'||s.shot_type==='on_target')x.on_target++;x.appearances.add(String(s.match_id));}return [...map.values()].map(x=>({...x,appearances:x.appearances.size}));}
function render(){const stat=document.querySelector('#statTabs .active')?.dataset.stat||'goals';const q=$('playerSearch').value.trim().toLowerCase();let rows=aggregate().filter(x=>x.name.toLowerCase().includes(q)||x.team.toLowerCase().includes(q)).sort((a,b)=>(b[stat]-a[stat])||a.name.localeCompare(b.name));$('statsStatus').textContent=rows.length?`${rows.length} wachezaji`:'Hakuna data iliyorekodiwa kwa kichujio hiki.';$('scorersList').innerHTML=rows.map((x,i)=>`<div class="stat-row"><span class="stat-rank">${i+1}</span><div class="stat-player"><a href="player.html?id=${encodeURIComponent(x.id)}"><strong>${esc(x.name)}</strong></a><a class="muted" href="team.html?id=${encodeURIComponent(x.clubId||'')}">${esc(x.team)}</a><small>${x.appearances} appearances • ${x.shots} shots • ${x.on_target} on target</small></div><strong class="stat-number">${x[stat]}</strong></div>`).join('');}
async function load(){try{[clubs,players,matches,competitions,allRows,shots]=await Promise.all([api('clubs','select=*'),api('players','select=*'),api('matches','select=*'),api('competitions','select=*'),api('match_events','select=*'),api('match_shots','select=match_id,player_id,shot_type')]);populateCompetitionFilter();const requested=selectedCompetition();const filter=$('competitionFilter');if(requested){const c=competitions.find(x=>String(x.id)===requested||String(x.name||x.title||'').toLowerCase()===requested.toLowerCase());if(c){filter.value=String(c.id);filter.dispatchEvent(new Event('change'));}else{const opt=[...filter.options].find(o=>o.textContent.trim().toLowerCase()===requested.toLowerCase());if(opt){filter.value=opt.value;filter.dispatchEvent(new Event('change'));}}}render();}catch(e){$('statsStatus').textContent='Data haikupatikana: '+e.message;}}
document.querySelectorAll('#statTabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#statTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render();}));$('competitionFilter').addEventListener('change',render);$('playerSearch').addEventListener('input',render);load();