const SUPABASE_URL='https://jjqhvruppafpumcthmwe.supabase.co';
const SUPABASE_KEY='sb_publishable_02hhRG8bgDOqSFxva8IMvQ_zWTLMa3G';
const app=document.getElementById('teamApp');const q=new URLSearchParams(location.search);const teamId=q.get('id');
function esc(s){return String(s??'').replace(/[&<>\"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[x]))}
async function api(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY}});if(!r.ok)throw new Error('Supabase: '+r.status);return r.json()}
function localTeams(){return JSON.parse(localStorage.getItem('afrn_master_teams')||'[]')} const num=v=>Number(v||0);
async function load(){
 if(!teamId){app.innerHTML='<div class="empty">Timu haijachaguliwa.</div>';return}
 const local=localTeams().find(t=>String(t.id)===String(teamId));let club=null,players=[],matches=[],clubs=[];
 try{clubs=await api('clubs?select=*&order=name');club=clubs.find(c=>String(c.id)===String(teamId)||String(c.afrn_club_id||'')===String(teamId)||String(c.name||'').toLowerCase()===String(teamId).toLowerCase())||null;if(club){const pid=encodeURIComponent(club.id);try{players=await api(`players?club_id=eq.${pid}&select=*`)}catch(e){}try{matches=await api(`matches?or=(home_team_id.eq.${pid},away_team_id.eq.${pid})&select=id,competition_id,home_team_id,away_team_id,match_date,match_time,venue,home_score,away_score,status&order=match_date.desc&limit=100`)}catch(e){}}}catch(e){}
 const t=local||club||{},name=t.jina||t.name||t.short_name||'Timu',division=t.division||'—',zone=t.zone||'—',clubCode=t.afrn_club_id||t.club_code||t.id||'—',logo=t.logo_url||'';
 const p=num(t.P),w=num(t.W||t.wins),d=num(t.D||t.draws),l=num(t.L||t.losses),gf=num(t.GF||t.goals_for),ga=num(t.GA||t.goals_against),pts=num(t.Pts||t.points),gd=gf-ga;
 const opponentName=id=>{const c=clubs.find(x=>String(x.id)===String(id));return c?.name||c?.short_name||'Mpinzani'};
 const completed=matches.filter(m=>(m.home_score!=null&&m.away_score!=null));
 let form=[];if(club){form=completed.slice(0,5).map(m=>{const home=String(m.home_team_id)===String(club.id),opp=home?m.away_team_id:m.home_team_id,hs=num(m.home_score),as=num(m.away_score),own=home?hs:as,other=home?as:hs,result=own>other?'W':own<other?'L':'D';return {result,opp:opponentName(opp),score:`${hs} - ${as}`,date:m.match_date,id:m.id}})}
 const h2h={};
 if(club){completed.forEach(m=>{const home=String(m.home_team_id)===String(club.id),opp=home?m.away_team_id:m.home_team_id;if(!opp)return;const key=String(opp);if(!h2h[key])h2h[key]={id:opp,name:opponentName(opp),played:0,wins:0,draws:0,losses:0,gf:0,ga:0,matches:[]};const x=h2h[key],hs=num(m.home_score),as=num(m.away_score),own=home?hs:as,other=home?as:hs;x.played++;x.gf+=own;x.ga+=other;if(own>other)x.wins++;else if(own===other)x.draws++;else x.losses++;x.matches.push({id:m.id,date:m.match_date,score:`${hs} - ${as}`,home:home});});}
 const h2hList=Object.values(h2h).sort((a,b)=>b.played-a.played||a.name.localeCompare(b.name));
 const h2hHtml=h2hList.length?`<div class="h2h-list">${h2hList.map(x=>`<article class="h2h-card"><div class="h2h-head"><div><b>${esc(name)}</b><small>vs</small><b>${esc(x.name)}</b></div><span>${x.played} mechi</span></div><div class="h2h-stats"><div><b>${x.wins}</b><small>Ushindi</small></div><div><b>${x.draws}</b><small>Sare</small></div><div><b>${x.losses}</b><small>Vipigo</small></div><div><b>${x.gf}:${x.ga}</b><small>GF:GA</small></div></div><div class="h2h-results">${x.matches.slice(0,10).map(m=>`<a href="match.html?id=${encodeURIComponent(m.id)}"><span>${esc(m.date||'—')}</span><b>${esc(m.score)}</b><small>${m.home?'Nyumbani':'Ugenini'}</small></a>`).join('')}</div></article>`).join('')}</div>`:'<div class="empty">Hakuna mechi za kihistoria zilizorekodiwa kati ya timu hii na wapinzani wake.</div>';
 const playerRows=players.map((x,i)=>{const n=x.name||x.full_name||x.player_name||[x.first_name,x.last_name].filter(Boolean).join(' ')||`Mchezaji ${i+1}`;return `<a class="club-row" href="player.html?id=${encodeURIComponent(x.id)}"><span>${i+1}. ${esc(n)}</span><small>${esc(x.position||x.role||'Mchezaji')}</small></a>`}).join('');
 const matchRows=matches.map(m=>{const home=String(m.home_team_id)===String(club?.id),opp=home?m.away_team_id:m.home_team_id,score=m.home_score==null?'—':`${m.home_score} - ${m.away_score}`;return `<a class="match-row-link" href="match.html?id=${encodeURIComponent(m.id)}"><span><small>${esc(m.match_date||'—')} • ${esc(m.status||'')}</small><strong>${home?'vs':'@'} ${esc(opponentName(opp))}</strong></span><b>${esc(score)}</b></a>`}).join('');
 const formHtml=form.length?`<div class="team-form"><div class="form-badges">${form.map(x=>`<span class="form-${x.result.toLowerCase()}" title="${esc(x.opp)} ${esc(x.score)}">${x.result}</span>`).join('')}</div>${form.map(x=>`<a class="form-match" href="match.html?id=${encodeURIComponent(x.id)}"><span>${esc(x.date||'—')} • ${esc(x.opp)}</span><b>${esc(x.score)}</b></a>`).join('')}</div>`:'<div class="empty">Hakuna mechi 5 zilizokamilika zilizopatikana bado.</div>';
 app.innerHTML=`<section class="competition-hero"><span class="eyebrow">AFRN TEAM CENTRE</span><div class="team-profile-head">${logo?`<img class="team-logo" src="${esc(logo)}" alt="">`:'<div class="team-logo team-logo-empty">⚽</div>'}<div><h1>${esc(name)}</h1><p class="match-meta">${esc(division)} • ${esc(zone)}</p><small>AFRN Club ID: ${esc(clubCode)}</small></div></div></section><nav class="fm-tabs"><a href="#overview">Muhtasari</a><a href="#squad">Kikosi</a><a href="#matches">Mechi</a><a href="#h2h">H2H</a><a href="#stats">Stats</a><a href="#history">Historia</a></nav>
 <section id="overview" class="card"><h2>🏟️ Muhtasari wa Timu</h2><div class="quick-grid"><div><b>${p}</b><span>Mechi</span></div><div><b>${w}</b><span>Ushindi</span></div><div><b>${d}</b><span>Sare</span></div><div><b>${l}</b><span>Kushindwa</span></div></div><h3>🔥 Team Form — Mechi 5 za mwisho</h3>${formHtml}</section>
 <section id="squad" class="card"><h2>👥 Kikosi</h2>${playerRows||'<div class="empty">Hakuna wachezaji waliounganishwa na timu hii bado.</div>'}</section>
 <section id="matches" class="card"><h2>📅 Mechi</h2>${matchRows||'<div class="empty">Hakuna mechi za timu hii zilizopatikana bado.</div>'}</section>
 <section id="h2h" class="card"><div class="section-head"><h2>🤝 Head-to-Head</h2><span class="event-count">${h2hList.length} wapinzani</span></div><p class="muted">Historia ya mechi zilizorekodiwa kati ya ${esc(name)} na kila mpinzani.</p>${h2hHtml}</section>
 <section id="stats" class="card"><h2>📊 Takwimu</h2><div class="quick-grid"><div><b>${gf}</b><span>Goals For</span></div><div><b>${ga}</b><span>Goals Against</span></div><div><b>${gd}</b><span>Goal Difference</span></div><div><b>${pts}</b><span>Points</span></div></div></section><section id="history" class="card"><h2>📚 Historia</h2><p class="muted">Historia ya timu itaunganishwa na misimu, mashindano, matokeo na vikombe.</p></section>`;
}
load();